[build]
  cmd = "go build -o ./tmp/server ./cmd/server"
  bin = "./tmp/server"
  include_ext = ["go"]
  exclude_dir = ["ent/enttest", "tmp", "fixtures"]
  delay = 500

[log]
  time = true

[color]
  app = "green"
