// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package sitemap

import (
	ent "github.com/mokevnin/1mail/ent"
	site "github.com/mokevnin/1mail/gen/site"
)

type ConverterImpl struct{}

func (c *ConverterImpl) ContactToResource(source *ent.Contact) site.SiteContactResource {
	var siteapiSiteContactResource site.SiteContactResource
	if source != nil {
		siteapiSiteContactResource.ID = entityID((*source).ID)
		siteapiSiteContactResource.Email = site.EmailAddress((*source).Email)
		siteapiSiteContactResource.FirstName = optNilString((*source).FirstName)
		siteapiSiteContactResource.LastName = optNilString((*source).LastName)
		siteapiSiteContactResource.TimeZone = optNilTimeZone((*source).TimeZone)
		siteapiSiteContactResource.CustomFields = contactCustomFields((*source).CustomFields)
		siteapiSiteContactResource.Status = site.SiteContactStatus((*source).Status)
		siteapiSiteContactResource.CreatedAt = timestamp((*source).CreatedAt)
		siteapiSiteContactResource.UpdatedAt = timestamp((*source).UpdatedAt)
	}
	return siteapiSiteContactResource
}
func (c *ConverterImpl) EventToResource(source *ent.Event) site.SiteEventResource {
	var siteapiSiteEventResource site.SiteEventResource
	if source != nil {
		siteapiSiteEventResource.ID = entityID((*source).ID)
		siteapiSiteEventResource.SubjectId = (*source).SubjectID
		siteapiSiteEventResource.Email = optNilString((*source).Email)
		siteapiSiteEventResource.Action = (*source).Action
		siteapiSiteEventResource.Properties = eventProperties((*source).Properties)
		siteapiSiteEventResource.OccurredAt = optNilTimestamp((*source).OccurredAt)
		siteapiSiteEventResource.CreatedAt = timestamp((*source).CreatedAt)
	}
	return siteapiSiteEventResource
}
func (c *ConverterImpl) SegmentToResource(source *ent.Segment) site.SiteSegmentResource {
	var siteapiSiteSegmentResource site.SiteSegmentResource
	if source != nil {
		siteapiSiteSegmentResource.ID = entityID((*source).ID)
		siteapiSiteSegmentResource.Name = (*source).Name
		siteapiSiteSegmentResource.Type = site.SiteSegmentType((*source).Type)
		siteapiSiteSegmentResource.Definition = optNilString((*source).Definition)
		siteapiSiteSegmentResource.CreatedAt = timestamp((*source).CreatedAt)
		siteapiSiteSegmentResource.UpdatedAt = timestamp((*source).UpdatedAt)
	}
	return siteapiSiteSegmentResource
}
func (c *ConverterImpl) TokenToResource(source *ent.ApiToken) site.SiteApiTokenResource {
	var siteapiSiteApiTokenResource site.SiteApiTokenResource
	if source != nil {
		siteapiSiteApiTokenResource.ID = entityID((*source).ID)
		siteapiSiteApiTokenResource.Name = (*source).Name
		siteapiSiteApiTokenResource.Prefix = (*source).Prefix
		if (*source).Scopes != nil {
			siteapiSiteApiTokenResource.Scopes = make([]string, len((*source).Scopes))
			for i := 0; i < len((*source).Scopes); i++ {
				siteapiSiteApiTokenResource.Scopes[i] = (*source).Scopes[i]
			}
		}
		siteapiSiteApiTokenResource.LastUsedAt = optNilTimestamp((*source).LastUsedAt)
		siteapiSiteApiTokenResource.ExpiresAt = optNilTimestamp((*source).ExpiresAt)
		siteapiSiteApiTokenResource.CreatedAt = timestamp((*source).CreatedAt)
	}
	return siteapiSiteApiTokenResource
}
func (c *ConverterImpl) UserToResource(source *ent.User) *site.SiteUserResource {
	var pSiteapiSiteUserResource *site.SiteUserResource
	if source != nil {
		var siteapiSiteUserResource site.SiteUserResource
		siteapiSiteUserResource.ID = entityID((*source).ID)
		siteapiSiteUserResource.Name = (*source).Name
		siteapiSiteUserResource.Email = site.EmailAddress((*source).Email)
		siteapiSiteUserResource.CreatedAt = timestamp((*source).CreatedAt)
		pSiteapiSiteUserResource = &siteapiSiteUserResource
	}
	return pSiteapiSiteUserResource
}
func (c *ConverterImpl) WorkspaceToResource(source *ent.Workspace) site.SiteWorkspaceResource {
	var siteapiSiteWorkspaceResource site.SiteWorkspaceResource
	if source != nil {
		siteapiSiteWorkspaceResource.ID = entityID((*source).ID)
		siteapiSiteWorkspaceResource.Name = (*source).Name
		siteapiSiteWorkspaceResource.Slug = (*source).Slug
		siteapiSiteWorkspaceResource.CollectKey = (*source).CollectKey
		siteapiSiteWorkspaceResource.CreatedAt = timestamp((*source).CreatedAt)
	}
	return siteapiSiteWorkspaceResource
}
