// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  translation: {
    actions: {
      cancel: 'Cancel'
      delete: 'Delete'
      edit: 'Edit'
      save: 'Save'
    }
    alerts: {
      deleteErrorTitle: 'Failed to delete contact'
      loadErrorTitle: 'Failed to load contacts'
      saveErrorTitle: 'Failed to save contact'
    }
    contacts: {
      addContact: 'Add contact'
      emptyState: 'Create your first contact.'
      noRecords: 'No contacts yet'
      statusFilter: 'Filter by status'
      title: 'Contacts'
    }
    form: {
      createTitle: 'New contact'
      deleteDescription: 'The contact will be deleted permanently.'
      deleteTitle: 'Delete contact'
      editTitle: 'Edit contact'
      invalidId: 'Invalid contact id'
    }
    notifications: {
      contactCreated: 'Contact created'
      contactDeleted: 'Contact deleted'
      contactUpdated: 'Contact updated'
      successTitle: 'Success'
    }
    status: {
      active: 'Active'
      all: 'All'
      unsubscribed: 'Unsubscribed'
    }
    table: {
      actions: 'Actions'
      email: 'Email'
      firstName: 'First name'
      lastName: 'Last name'
      status: 'Status'
      timeZone: 'Time zone'
    }
  }
}

export default Resources
