-- +goose Up
-- Modify "workspaces" table
ALTER TABLE "public"."workspaces" ADD COLUMN "suspended_at" timestamptz NULL, ADD COLUMN "suspended_by" character varying NULL, ADD COLUMN "suspension_reason" character varying NULL;
-- Create "outbound_messages" table
CREATE TABLE "public"."outbound_messages" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "kind" character varying NOT NULL, "idempotency_key" character varying NOT NULL, "channel" character varying NOT NULL DEFAULT 'email', "destination" character varying NOT NULL, "contact_id" bigint NULL, "sending_source" character varying NULL, "sending_domain" character varying NULL, "provider_message_id" character varying NULL, "status" character varying NOT NULL DEFAULT 'pending', "reason" character varying NULL, "claimed_at" timestamptz NOT NULL, "sent_at" timestamptz NULL, "broadcast_id" bigint NULL, "broadcast_recipient_id" bigint NULL, "automation_id" bigint NULL, "automation_run_id" bigint NULL, "automation_step" bigint NULL, "template_id" bigint NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "workspace_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "outbound_messages_workspaces_outbound_messages" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "outbound_messages_workspace_id_idempotency_key" to table: "outbound_messages"
CREATE UNIQUE INDEX "outbound_messages_workspace_id_idempotency_key" ON "public"."outbound_messages" ("workspace_id", "idempotency_key");
-- Create index "outboundmessage_workspace_id_kind_created_at" to table: "outbound_messages"
CREATE INDEX "outboundmessage_workspace_id_kind_created_at" ON "public"."outbound_messages" ("workspace_id", "kind", "created_at");
-- Create index "outboundmessage_workspace_id_sending_domain_created_at" to table: "outbound_messages"
CREATE INDEX "outboundmessage_workspace_id_sending_domain_created_at" ON "public"."outbound_messages" ("workspace_id", "sending_domain", "created_at");

-- +goose Down
