-- Create "integrations" table
CREATE TABLE "public"."integrations" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "channel" character varying NOT NULL DEFAULT 'email',
  "provider" character varying NOT NULL,
  "config_encrypted" character varying NOT NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "workspace_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "integrations_workspaces_integrations" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "integration_workspace_id_channel" to table: "integrations"
CREATE UNIQUE INDEX "integration_workspace_id_channel" ON "public"."integrations" ("workspace_id", "channel") WHERE is_default;
