-- Create "broadcasts" table
CREATE TABLE "public"."broadcasts" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" character varying NOT NULL,
  "subject" character varying NOT NULL DEFAULT '',
  "from_name" character varying NULL,
  "from_email" character varying NULL,
  "body_html" character varying NOT NULL DEFAULT '',
  "body_text" character varying NOT NULL DEFAULT '',
  "segment_id" bigint NULL,
  "integration_id" bigint NULL,
  "status" character varying NOT NULL DEFAULT 'draft',
  "scheduled_at" timestamptz NULL,
  "sent_at" timestamptz NULL,
  "recipients_total" bigint NOT NULL DEFAULT 0,
  "sent_count" bigint NOT NULL DEFAULT 0,
  "opened_count" bigint NOT NULL DEFAULT 0,
  "clicked_count" bigint NOT NULL DEFAULT 0,
  "unsubscribed_count" bigint NOT NULL DEFAULT 0,
  "failed_count" bigint NOT NULL DEFAULT 0,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "workspace_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "broadcasts_workspaces_broadcasts" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "broadcast_workspace_id" to table: "broadcasts"
CREATE INDEX "broadcast_workspace_id" ON "public"."broadcasts" ("workspace_id");
-- Create "broadcast_recipients" table
CREATE TABLE "public"."broadcast_recipients" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "contact_id" bigint NOT NULL,
  "status" character varying NOT NULL DEFAULT 'pending',
  "error" character varying NULL,
  "sent_at" timestamptz NULL,
  "opened_at" timestamptz NULL,
  "clicked_at" timestamptz NULL,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "broadcast_id" bigint NOT NULL,
  "workspace_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "broadcast_recipients_broadcasts_recipients" FOREIGN KEY ("broadcast_id") REFERENCES "public"."broadcasts" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION,
  CONSTRAINT "broadcast_recipients_workspaces_broadcast_recipients" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "broadcast_recipients_broadcast_id_contact_id" to table: "broadcast_recipients"
CREATE UNIQUE INDEX "broadcast_recipients_broadcast_id_contact_id" ON "public"."broadcast_recipients" ("broadcast_id", "contact_id");
-- Create index "broadcastrecipient_broadcast_id" to table: "broadcast_recipients"
CREATE INDEX "broadcastrecipient_broadcast_id" ON "public"."broadcast_recipients" ("broadcast_id");
