-- Create "webhook_endpoints" table
CREATE TABLE "public"."webhook_endpoints" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "url" character varying NOT NULL,
  "secret_encrypted" character varying NOT NULL,
  "event_types" jsonb NULL,
  "enabled" boolean NOT NULL DEFAULT true,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "workspace_id" bigint NOT NULL,
  PRIMARY KEY ("id"),
  CONSTRAINT "webhook_endpoints_workspaces_webhook_endpoints" FOREIGN KEY ("workspace_id") REFERENCES "public"."workspaces" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION
);
-- Create index "webhookendpoint_workspace_id" to table: "webhook_endpoints"
CREATE INDEX "webhookendpoint_workspace_id" ON "public"."webhook_endpoints" ("workspace_id");
-- Create index "webhookendpoint_workspace_id_enabled" to table: "webhook_endpoints"
CREATE INDEX "webhookendpoint_workspace_id_enabled" ON "public"."webhook_endpoints" ("workspace_id", "enabled");
