// Code generated by ent, DO NOT EDIT.

package sendlimiter

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mokevnin/1mail/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldUpdatedAt, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldWorkspaceID, v))
}

// IntegrationID applies equality check predicate on the "integration_id" field. It's identical to IntegrationIDEQ.
func IntegrationID(v int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldIntegrationID, v))
}

// SecondFill applies equality check predicate on the "second_fill" field. It's identical to SecondFillEQ.
func SecondFill(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldSecondFill, v))
}

// DayFill applies equality check predicate on the "day_fill" field. It's identical to DayFillEQ.
func DayFill(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldDayFill, v))
}

// RefilledAt applies equality check predicate on the "refilled_at" field. It's identical to RefilledAtEQ.
func RefilledAt(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldRefilledAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldLTE(FieldUpdatedAt, v))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// IntegrationIDEQ applies the EQ predicate on the "integration_id" field.
func IntegrationIDEQ(v int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldIntegrationID, v))
}

// IntegrationIDNEQ applies the NEQ predicate on the "integration_id" field.
func IntegrationIDNEQ(v int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNEQ(FieldIntegrationID, v))
}

// IntegrationIDIn applies the In predicate on the "integration_id" field.
func IntegrationIDIn(vs ...int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldIn(FieldIntegrationID, vs...))
}

// IntegrationIDNotIn applies the NotIn predicate on the "integration_id" field.
func IntegrationIDNotIn(vs ...int64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNotIn(FieldIntegrationID, vs...))
}

// SecondFillEQ applies the EQ predicate on the "second_fill" field.
func SecondFillEQ(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldSecondFill, v))
}

// SecondFillNEQ applies the NEQ predicate on the "second_fill" field.
func SecondFillNEQ(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNEQ(FieldSecondFill, v))
}

// SecondFillIn applies the In predicate on the "second_fill" field.
func SecondFillIn(vs ...float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldIn(FieldSecondFill, vs...))
}

// SecondFillNotIn applies the NotIn predicate on the "second_fill" field.
func SecondFillNotIn(vs ...float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNotIn(FieldSecondFill, vs...))
}

// SecondFillGT applies the GT predicate on the "second_fill" field.
func SecondFillGT(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldGT(FieldSecondFill, v))
}

// SecondFillGTE applies the GTE predicate on the "second_fill" field.
func SecondFillGTE(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldGTE(FieldSecondFill, v))
}

// SecondFillLT applies the LT predicate on the "second_fill" field.
func SecondFillLT(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldLT(FieldSecondFill, v))
}

// SecondFillLTE applies the LTE predicate on the "second_fill" field.
func SecondFillLTE(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldLTE(FieldSecondFill, v))
}

// DayFillEQ applies the EQ predicate on the "day_fill" field.
func DayFillEQ(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldDayFill, v))
}

// DayFillNEQ applies the NEQ predicate on the "day_fill" field.
func DayFillNEQ(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNEQ(FieldDayFill, v))
}

// DayFillIn applies the In predicate on the "day_fill" field.
func DayFillIn(vs ...float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldIn(FieldDayFill, vs...))
}

// DayFillNotIn applies the NotIn predicate on the "day_fill" field.
func DayFillNotIn(vs ...float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNotIn(FieldDayFill, vs...))
}

// DayFillGT applies the GT predicate on the "day_fill" field.
func DayFillGT(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldGT(FieldDayFill, v))
}

// DayFillGTE applies the GTE predicate on the "day_fill" field.
func DayFillGTE(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldGTE(FieldDayFill, v))
}

// DayFillLT applies the LT predicate on the "day_fill" field.
func DayFillLT(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldLT(FieldDayFill, v))
}

// DayFillLTE applies the LTE predicate on the "day_fill" field.
func DayFillLTE(v float64) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldLTE(FieldDayFill, v))
}

// RefilledAtEQ applies the EQ predicate on the "refilled_at" field.
func RefilledAtEQ(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldEQ(FieldRefilledAt, v))
}

// RefilledAtNEQ applies the NEQ predicate on the "refilled_at" field.
func RefilledAtNEQ(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNEQ(FieldRefilledAt, v))
}

// RefilledAtIn applies the In predicate on the "refilled_at" field.
func RefilledAtIn(vs ...time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldIn(FieldRefilledAt, vs...))
}

// RefilledAtNotIn applies the NotIn predicate on the "refilled_at" field.
func RefilledAtNotIn(vs ...time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldNotIn(FieldRefilledAt, vs...))
}

// RefilledAtGT applies the GT predicate on the "refilled_at" field.
func RefilledAtGT(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldGT(FieldRefilledAt, v))
}

// RefilledAtGTE applies the GTE predicate on the "refilled_at" field.
func RefilledAtGTE(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldGTE(FieldRefilledAt, v))
}

// RefilledAtLT applies the LT predicate on the "refilled_at" field.
func RefilledAtLT(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldLT(FieldRefilledAt, v))
}

// RefilledAtLTE applies the LTE predicate on the "refilled_at" field.
func RefilledAtLTE(v time.Time) predicate.SendLimiter {
	return predicate.SendLimiter(sql.FieldLTE(FieldRefilledAt, v))
}

// HasWorkspace applies the HasEdge predicate on the "workspace" edge.
func HasWorkspace() predicate.SendLimiter {
	return predicate.SendLimiter(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkspaceTable, WorkspaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspaceWith applies the HasEdge predicate on the "workspace" edge with a given conditions (other predicates).
func HasWorkspaceWith(preds ...predicate.Workspace) predicate.SendLimiter {
	return predicate.SendLimiter(func(s *sql.Selector) {
		step := newWorkspaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasIntegration applies the HasEdge predicate on the "integration" edge.
func HasIntegration() predicate.SendLimiter {
	return predicate.SendLimiter(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, IntegrationTable, IntegrationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasIntegrationWith applies the HasEdge predicate on the "integration" edge with a given conditions (other predicates).
func HasIntegrationWith(preds ...predicate.Integration) predicate.SendLimiter {
	return predicate.SendLimiter(func(s *sql.Selector) {
		step := newIntegrationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SendLimiter) predicate.SendLimiter {
	return predicate.SendLimiter(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SendLimiter) predicate.SendLimiter {
	return predicate.SendLimiter(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SendLimiter) predicate.SendLimiter {
	return predicate.SendLimiter(sql.NotPredicates(p))
}
