// Code generated by ent, DO NOT EDIT.

package automationrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mokevnin/1mail/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldLTE(FieldID, id))
}

// AutomationID applies equality check predicate on the "automation_id" field. It's identical to AutomationIDEQ.
func AutomationID(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldAutomationID, v))
}

// ContactID applies equality check predicate on the "contact_id" field. It's identical to ContactIDEQ.
func ContactID(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldContactID, v))
}

// WorkspaceID applies equality check predicate on the "workspace_id" field. It's identical to WorkspaceIDEQ.
func WorkspaceID(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldWorkspaceID, v))
}

// CurrentStep applies equality check predicate on the "current_step" field. It's identical to CurrentStepEQ.
func CurrentStep(v int) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldCurrentStep, v))
}

// ResumeAt applies equality check predicate on the "resume_at" field. It's identical to ResumeAtEQ.
func ResumeAt(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldResumeAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldUpdatedAt, v))
}

// AutomationIDEQ applies the EQ predicate on the "automation_id" field.
func AutomationIDEQ(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldAutomationID, v))
}

// AutomationIDNEQ applies the NEQ predicate on the "automation_id" field.
func AutomationIDNEQ(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNEQ(FieldAutomationID, v))
}

// AutomationIDIn applies the In predicate on the "automation_id" field.
func AutomationIDIn(vs ...int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldIn(FieldAutomationID, vs...))
}

// AutomationIDNotIn applies the NotIn predicate on the "automation_id" field.
func AutomationIDNotIn(vs ...int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNotIn(FieldAutomationID, vs...))
}

// ContactIDEQ applies the EQ predicate on the "contact_id" field.
func ContactIDEQ(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldContactID, v))
}

// ContactIDNEQ applies the NEQ predicate on the "contact_id" field.
func ContactIDNEQ(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNEQ(FieldContactID, v))
}

// ContactIDIn applies the In predicate on the "contact_id" field.
func ContactIDIn(vs ...int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldIn(FieldContactID, vs...))
}

// ContactIDNotIn applies the NotIn predicate on the "contact_id" field.
func ContactIDNotIn(vs ...int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNotIn(FieldContactID, vs...))
}

// ContactIDGT applies the GT predicate on the "contact_id" field.
func ContactIDGT(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldGT(FieldContactID, v))
}

// ContactIDGTE applies the GTE predicate on the "contact_id" field.
func ContactIDGTE(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldGTE(FieldContactID, v))
}

// ContactIDLT applies the LT predicate on the "contact_id" field.
func ContactIDLT(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldLT(FieldContactID, v))
}

// ContactIDLTE applies the LTE predicate on the "contact_id" field.
func ContactIDLTE(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldLTE(FieldContactID, v))
}

// WorkspaceIDEQ applies the EQ predicate on the "workspace_id" field.
func WorkspaceIDEQ(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldWorkspaceID, v))
}

// WorkspaceIDNEQ applies the NEQ predicate on the "workspace_id" field.
func WorkspaceIDNEQ(v int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNEQ(FieldWorkspaceID, v))
}

// WorkspaceIDIn applies the In predicate on the "workspace_id" field.
func WorkspaceIDIn(vs ...int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldIn(FieldWorkspaceID, vs...))
}

// WorkspaceIDNotIn applies the NotIn predicate on the "workspace_id" field.
func WorkspaceIDNotIn(vs ...int64) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNotIn(FieldWorkspaceID, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNotIn(FieldStatus, vs...))
}

// CurrentStepEQ applies the EQ predicate on the "current_step" field.
func CurrentStepEQ(v int) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldCurrentStep, v))
}

// CurrentStepNEQ applies the NEQ predicate on the "current_step" field.
func CurrentStepNEQ(v int) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNEQ(FieldCurrentStep, v))
}

// CurrentStepIn applies the In predicate on the "current_step" field.
func CurrentStepIn(vs ...int) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldIn(FieldCurrentStep, vs...))
}

// CurrentStepNotIn applies the NotIn predicate on the "current_step" field.
func CurrentStepNotIn(vs ...int) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNotIn(FieldCurrentStep, vs...))
}

// CurrentStepGT applies the GT predicate on the "current_step" field.
func CurrentStepGT(v int) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldGT(FieldCurrentStep, v))
}

// CurrentStepGTE applies the GTE predicate on the "current_step" field.
func CurrentStepGTE(v int) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldGTE(FieldCurrentStep, v))
}

// CurrentStepLT applies the LT predicate on the "current_step" field.
func CurrentStepLT(v int) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldLT(FieldCurrentStep, v))
}

// CurrentStepLTE applies the LTE predicate on the "current_step" field.
func CurrentStepLTE(v int) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldLTE(FieldCurrentStep, v))
}

// ResumeAtEQ applies the EQ predicate on the "resume_at" field.
func ResumeAtEQ(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldResumeAt, v))
}

// ResumeAtNEQ applies the NEQ predicate on the "resume_at" field.
func ResumeAtNEQ(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNEQ(FieldResumeAt, v))
}

// ResumeAtIn applies the In predicate on the "resume_at" field.
func ResumeAtIn(vs ...time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldIn(FieldResumeAt, vs...))
}

// ResumeAtNotIn applies the NotIn predicate on the "resume_at" field.
func ResumeAtNotIn(vs ...time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNotIn(FieldResumeAt, vs...))
}

// ResumeAtGT applies the GT predicate on the "resume_at" field.
func ResumeAtGT(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldGT(FieldResumeAt, v))
}

// ResumeAtGTE applies the GTE predicate on the "resume_at" field.
func ResumeAtGTE(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldGTE(FieldResumeAt, v))
}

// ResumeAtLT applies the LT predicate on the "resume_at" field.
func ResumeAtLT(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldLT(FieldResumeAt, v))
}

// ResumeAtLTE applies the LTE predicate on the "resume_at" field.
func ResumeAtLTE(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldLTE(FieldResumeAt, v))
}

// ResumeAtIsNil applies the IsNil predicate on the "resume_at" field.
func ResumeAtIsNil() predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldIsNull(FieldResumeAt))
}

// ResumeAtNotNil applies the NotNil predicate on the "resume_at" field.
func ResumeAtNotNil() predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNotNull(FieldResumeAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AutomationRun {
	return predicate.AutomationRun(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasAutomation applies the HasEdge predicate on the "automation" edge.
func HasAutomation() predicate.AutomationRun {
	return predicate.AutomationRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AutomationTable, AutomationColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAutomationWith applies the HasEdge predicate on the "automation" edge with a given conditions (other predicates).
func HasAutomationWith(preds ...predicate.Automation) predicate.AutomationRun {
	return predicate.AutomationRun(func(s *sql.Selector) {
		step := newAutomationStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasWorkspace applies the HasEdge predicate on the "workspace" edge.
func HasWorkspace() predicate.AutomationRun {
	return predicate.AutomationRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WorkspaceTable, WorkspaceColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWorkspaceWith applies the HasEdge predicate on the "workspace" edge with a given conditions (other predicates).
func HasWorkspaceWith(preds ...predicate.Workspace) predicate.AutomationRun {
	return predicate.AutomationRun(func(s *sql.Selector) {
		step := newWorkspaceStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AutomationRun) predicate.AutomationRun {
	return predicate.AutomationRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AutomationRun) predicate.AutomationRun {
	return predicate.AutomationRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AutomationRun) predicate.AutomationRun {
	return predicate.AutomationRun(sql.NotPredicates(p))
}
