// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package jobs_test

import (
	"context"
	"github.com/mokevnin/1mail/ent"
	"github.com/mokevnin/1mail/internal/messaging"
	"github.com/mokevnin/1mail/internal/outbound"
	"sync"
)

// Ensure, that SendersMock does implement outbound.Senders.
// If this is not the case, regenerate this file with moq.
var _ outbound.Senders = &SendersMock{}

// SendersMock is a mock implementation of outbound.Senders.
//
//	func TestSomethingThatUsesSenders(t *testing.T) {
//
//		// make and configure a mocked outbound.Senders
//		mockedSenders := &SendersMock{
//			EmailSenderFunc: func(ctx context.Context, s *ent.Scoped) (messaging.EmailSender, error) {
//				panic("mock out the EmailSender method")
//			},
//		}
//
//		// use mockedSenders in code that requires outbound.Senders
//		// and then make assertions.
//
//	}
type SendersMock struct {
	// EmailSenderFunc mocks the EmailSender method.
	EmailSenderFunc func(ctx context.Context, s *ent.Scoped) (messaging.EmailSender, error)

	// calls tracks calls to the methods.
	calls struct {
		// EmailSender holds details about calls to the EmailSender method.
		EmailSender []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// S is the s argument value.
			S *ent.Scoped
		}
	}
	lockEmailSender sync.RWMutex
}

// EmailSender calls EmailSenderFunc.
func (mock *SendersMock) EmailSender(ctx context.Context, s *ent.Scoped) (messaging.EmailSender, error) {
	if mock.EmailSenderFunc == nil {
		panic("SendersMock.EmailSenderFunc: method is nil but Senders.EmailSender was just called")
	}
	callInfo := struct {
		Ctx context.Context
		S   *ent.Scoped
	}{
		Ctx: ctx,
		S:   s,
	}
	mock.lockEmailSender.Lock()
	mock.calls.EmailSender = append(mock.calls.EmailSender, callInfo)
	mock.lockEmailSender.Unlock()
	return mock.EmailSenderFunc(ctx, s)
}

// EmailSenderCalls gets all the calls that were made to EmailSender.
// Check the length with:
//
//	len(mockedSenders.EmailSenderCalls())
func (mock *SendersMock) EmailSenderCalls() []struct {
	Ctx context.Context
	S   *ent.Scoped
} {
	var calls []struct {
		Ctx context.Context
		S   *ent.Scoped
	}
	mock.lockEmailSender.RLock()
	calls = mock.calls.EmailSender
	mock.lockEmailSender.RUnlock()
	return calls
}
