// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mokevnin/1mail/ent/authattempt"
	"github.com/mokevnin/1mail/ent/predicate"
)

// AuthAttemptUpdate is the builder for updating AuthAttempt entities.
type AuthAttemptUpdate struct {
	config
	hooks     []Hook
	mutation  *AuthAttemptMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the AuthAttemptUpdate builder.
func (_u *AuthAttemptUpdate) Where(ps ...predicate.AuthAttempt) *AuthAttemptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthAttemptUpdate) SetUpdatedAt(v time.Time) *AuthAttemptUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFailures sets the "failures" field.
func (_u *AuthAttemptUpdate) SetFailures(v int) *AuthAttemptUpdate {
	_u.mutation.ResetFailures()
	_u.mutation.SetFailures(v)
	return _u
}

// SetNillableFailures sets the "failures" field if the given value is not nil.
func (_u *AuthAttemptUpdate) SetNillableFailures(v *int) *AuthAttemptUpdate {
	if v != nil {
		_u.SetFailures(*v)
	}
	return _u
}

// AddFailures adds value to the "failures" field.
func (_u *AuthAttemptUpdate) AddFailures(v int) *AuthAttemptUpdate {
	_u.mutation.AddFailures(v)
	return _u
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (_u *AuthAttemptUpdate) SetLastAttemptAt(v time.Time) *AuthAttemptUpdate {
	_u.mutation.SetLastAttemptAt(v)
	return _u
}

// SetNillableLastAttemptAt sets the "last_attempt_at" field if the given value is not nil.
func (_u *AuthAttemptUpdate) SetNillableLastAttemptAt(v *time.Time) *AuthAttemptUpdate {
	if v != nil {
		_u.SetLastAttemptAt(*v)
	}
	return _u
}

// Mutation returns the AuthAttemptMutation object of the builder.
func (_u *AuthAttemptUpdate) Mutation() *AuthAttemptMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthAttemptUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthAttemptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthAttemptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthAttemptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthAttemptUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authattempt.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AuthAttemptUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AuthAttemptUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AuthAttemptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(authattempt.Table, authattempt.Columns, sqlgraph.NewFieldSpec(authattempt.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authattempt.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Failures(); ok {
		_spec.SetField(authattempt.FieldFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailures(); ok {
		_spec.AddField(authattempt.FieldFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastAttemptAt(); ok {
		_spec.SetField(authattempt.FieldLastAttemptAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthAttemptUpdateOne is the builder for updating a single AuthAttempt entity.
type AuthAttemptUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *AuthAttemptMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthAttemptUpdateOne) SetUpdatedAt(v time.Time) *AuthAttemptUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFailures sets the "failures" field.
func (_u *AuthAttemptUpdateOne) SetFailures(v int) *AuthAttemptUpdateOne {
	_u.mutation.ResetFailures()
	_u.mutation.SetFailures(v)
	return _u
}

// SetNillableFailures sets the "failures" field if the given value is not nil.
func (_u *AuthAttemptUpdateOne) SetNillableFailures(v *int) *AuthAttemptUpdateOne {
	if v != nil {
		_u.SetFailures(*v)
	}
	return _u
}

// AddFailures adds value to the "failures" field.
func (_u *AuthAttemptUpdateOne) AddFailures(v int) *AuthAttemptUpdateOne {
	_u.mutation.AddFailures(v)
	return _u
}

// SetLastAttemptAt sets the "last_attempt_at" field.
func (_u *AuthAttemptUpdateOne) SetLastAttemptAt(v time.Time) *AuthAttemptUpdateOne {
	_u.mutation.SetLastAttemptAt(v)
	return _u
}

// SetNillableLastAttemptAt sets the "last_attempt_at" field if the given value is not nil.
func (_u *AuthAttemptUpdateOne) SetNillableLastAttemptAt(v *time.Time) *AuthAttemptUpdateOne {
	if v != nil {
		_u.SetLastAttemptAt(*v)
	}
	return _u
}

// Mutation returns the AuthAttemptMutation object of the builder.
func (_u *AuthAttemptUpdateOne) Mutation() *AuthAttemptMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthAttemptUpdate builder.
func (_u *AuthAttemptUpdateOne) Where(ps ...predicate.AuthAttempt) *AuthAttemptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthAttemptUpdateOne) Select(field string, fields ...string) *AuthAttemptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthAttempt entity.
func (_u *AuthAttemptUpdateOne) Save(ctx context.Context) (*AuthAttempt, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthAttemptUpdateOne) SaveX(ctx context.Context) *AuthAttempt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthAttemptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthAttemptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AuthAttemptUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authattempt.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *AuthAttemptUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *AuthAttemptUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *AuthAttemptUpdateOne) sqlSave(ctx context.Context) (_node *AuthAttempt, err error) {
	_spec := sqlgraph.NewUpdateSpec(authattempt.Table, authattempt.Columns, sqlgraph.NewFieldSpec(authattempt.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthAttempt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authattempt.FieldID)
		for _, f := range fields {
			if !authattempt.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authattempt.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Failures(); ok {
		_spec.SetField(authattempt.FieldFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedFailures(); ok {
		_spec.AddField(authattempt.FieldFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastAttemptAt(); ok {
		_spec.SetField(authattempt.FieldLastAttemptAt, field.TypeTime, value)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &AuthAttempt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
