// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mokevnin/1mail/ent/confirmation"
	"github.com/mokevnin/1mail/ent/workspace"
)

// Confirmation is the model entity for the Confirmation schema.
type Confirmation struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Channel holds the value of the "channel" field.
	Channel confirmation.Channel `json:"channel,omitempty"`
	// Destination holds the value of the "destination" field.
	Destination string `json:"destination,omitempty"`
	// Provenance holds the value of the "provenance" field.
	Provenance confirmation.Provenance `json:"provenance,omitempty"`
	// ContactID holds the value of the "contact_id" field.
	ContactID *int64 `json:"contact_id,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID int64 `json:"workspace_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ConfirmationQuery when eager-loading is set.
	Edges        ConfirmationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ConfirmationEdges holds the relations/edges for other nodes in the graph.
type ConfirmationEdges struct {
	// Workspace holds the value of the workspace edge.
	Workspace *Workspace `json:"workspace,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// WorkspaceOrErr returns the Workspace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ConfirmationEdges) WorkspaceOrErr() (*Workspace, error) {
	if e.Workspace != nil {
		return e.Workspace, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workspace.Label}
	}
	return nil, &NotLoadedError{edge: "workspace"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Confirmation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case confirmation.FieldID, confirmation.FieldContactID, confirmation.FieldWorkspaceID:
			values[i] = new(sql.NullInt64)
		case confirmation.FieldChannel, confirmation.FieldDestination, confirmation.FieldProvenance:
			values[i] = new(sql.NullString)
		case confirmation.FieldCreatedAt, confirmation.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Confirmation fields.
func (_m *Confirmation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case confirmation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case confirmation.FieldChannel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field channel", values[i])
			} else if value.Valid {
				_m.Channel = confirmation.Channel(value.String)
			}
		case confirmation.FieldDestination:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field destination", values[i])
			} else if value.Valid {
				_m.Destination = value.String
			}
		case confirmation.FieldProvenance:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provenance", values[i])
			} else if value.Valid {
				_m.Provenance = confirmation.Provenance(value.String)
			}
		case confirmation.FieldContactID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field contact_id", values[i])
			} else if value.Valid {
				_m.ContactID = new(int64)
				*_m.ContactID = value.Int64
			}
		case confirmation.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				_m.WorkspaceID = value.Int64
			}
		case confirmation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case confirmation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Confirmation.
// This includes values selected through modifiers, order, etc.
func (_m *Confirmation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkspace queries the "workspace" edge of the Confirmation entity.
func (_m *Confirmation) QueryWorkspace() *WorkspaceQuery {
	return NewConfirmationClient(_m.config).QueryWorkspace(_m)
}

// Update returns a builder for updating this Confirmation.
// Note that you need to call Confirmation.Unwrap() before calling this method if this Confirmation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Confirmation) Update() *ConfirmationUpdateOne {
	return NewConfirmationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Confirmation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Confirmation) Unwrap() *Confirmation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Confirmation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Confirmation) String() string {
	var builder strings.Builder
	builder.WriteString("Confirmation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("channel=")
	builder.WriteString(fmt.Sprintf("%v", _m.Channel))
	builder.WriteString(", ")
	builder.WriteString("destination=")
	builder.WriteString(_m.Destination)
	builder.WriteString(", ")
	builder.WriteString("provenance=")
	builder.WriteString(fmt.Sprintf("%v", _m.Provenance))
	builder.WriteString(", ")
	if v := _m.ContactID; v != nil {
		builder.WriteString("contact_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("workspace_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkspaceID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Confirmations is a parsable slice of Confirmation.
type Confirmations []*Confirmation
