// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mokevnin/1mail/ent/segment"
	"github.com/mokevnin/1mail/ent/workspace"
)

// Segment is the model entity for the Segment schema.
type Segment struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type segment.Type `json:"type,omitempty"`
	// Definition holds the value of the "definition" field.
	Definition *string `json:"definition,omitempty"`
	// WorkspaceID holds the value of the "workspace_id" field.
	WorkspaceID int64 `json:"workspace_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SegmentQuery when eager-loading is set.
	Edges        SegmentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SegmentEdges holds the relations/edges for other nodes in the graph.
type SegmentEdges struct {
	// Workspace holds the value of the workspace edge.
	Workspace *Workspace `json:"workspace,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// WorkspaceOrErr returns the Workspace value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SegmentEdges) WorkspaceOrErr() (*Workspace, error) {
	if e.Workspace != nil {
		return e.Workspace, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: workspace.Label}
	}
	return nil, &NotLoadedError{edge: "workspace"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Segment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case segment.FieldID, segment.FieldWorkspaceID:
			values[i] = new(sql.NullInt64)
		case segment.FieldName, segment.FieldType, segment.FieldDefinition:
			values[i] = new(sql.NullString)
		case segment.FieldCreatedAt, segment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Segment fields.
func (_m *Segment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case segment.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case segment.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case segment.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = segment.Type(value.String)
			}
		case segment.FieldDefinition:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field definition", values[i])
			} else if value.Valid {
				_m.Definition = new(string)
				*_m.Definition = value.String
			}
		case segment.FieldWorkspaceID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_id", values[i])
			} else if value.Valid {
				_m.WorkspaceID = value.Int64
			}
		case segment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case segment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Segment.
// This includes values selected through modifiers, order, etc.
func (_m *Segment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWorkspace queries the "workspace" edge of the Segment entity.
func (_m *Segment) QueryWorkspace() *WorkspaceQuery {
	return NewSegmentClient(_m.config).QueryWorkspace(_m)
}

// Update returns a builder for updating this Segment.
// Note that you need to call Segment.Unwrap() before calling this method if this Segment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Segment) Update() *SegmentUpdateOne {
	return NewSegmentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Segment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Segment) Unwrap() *Segment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Segment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Segment) String() string {
	var builder strings.Builder
	builder.WriteString("Segment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	if v := _m.Definition; v != nil {
		builder.WriteString("definition=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("workspace_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkspaceID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Segments is a parsable slice of Segment.
type Segments []*Segment
