// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mokevnin/1mail/ent/predicate"
	"github.com/mokevnin/1mail/ent/sendlimiter"
	"github.com/mokevnin/1mail/ent/workspace"
)

// SendLimiterUpdate is the builder for updating SendLimiter entities.
type SendLimiterUpdate struct {
	config
	hooks     []Hook
	mutation  *SendLimiterMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the SendLimiterUpdate builder.
func (_u *SendLimiterUpdate) Where(ps ...predicate.SendLimiter) *SendLimiterUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SendLimiterUpdate) SetUpdatedAt(v time.Time) *SendLimiterUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *SendLimiterUpdate) SetWorkspaceID(v int64) *SendLimiterUpdate {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *SendLimiterUpdate) SetNillableWorkspaceID(v *int64) *SendLimiterUpdate {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetSecondFill sets the "second_fill" field.
func (_u *SendLimiterUpdate) SetSecondFill(v float64) *SendLimiterUpdate {
	_u.mutation.ResetSecondFill()
	_u.mutation.SetSecondFill(v)
	return _u
}

// SetNillableSecondFill sets the "second_fill" field if the given value is not nil.
func (_u *SendLimiterUpdate) SetNillableSecondFill(v *float64) *SendLimiterUpdate {
	if v != nil {
		_u.SetSecondFill(*v)
	}
	return _u
}

// AddSecondFill adds value to the "second_fill" field.
func (_u *SendLimiterUpdate) AddSecondFill(v float64) *SendLimiterUpdate {
	_u.mutation.AddSecondFill(v)
	return _u
}

// SetDayFill sets the "day_fill" field.
func (_u *SendLimiterUpdate) SetDayFill(v float64) *SendLimiterUpdate {
	_u.mutation.ResetDayFill()
	_u.mutation.SetDayFill(v)
	return _u
}

// SetNillableDayFill sets the "day_fill" field if the given value is not nil.
func (_u *SendLimiterUpdate) SetNillableDayFill(v *float64) *SendLimiterUpdate {
	if v != nil {
		_u.SetDayFill(*v)
	}
	return _u
}

// AddDayFill adds value to the "day_fill" field.
func (_u *SendLimiterUpdate) AddDayFill(v float64) *SendLimiterUpdate {
	_u.mutation.AddDayFill(v)
	return _u
}

// SetRefilledAt sets the "refilled_at" field.
func (_u *SendLimiterUpdate) SetRefilledAt(v time.Time) *SendLimiterUpdate {
	_u.mutation.SetRefilledAt(v)
	return _u
}

// SetNillableRefilledAt sets the "refilled_at" field if the given value is not nil.
func (_u *SendLimiterUpdate) SetNillableRefilledAt(v *time.Time) *SendLimiterUpdate {
	if v != nil {
		_u.SetRefilledAt(*v)
	}
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *SendLimiterUpdate) SetWorkspace(v *Workspace) *SendLimiterUpdate {
	return _u.SetWorkspaceID(v.ID)
}

// Mutation returns the SendLimiterMutation object of the builder.
func (_u *SendLimiterUpdate) Mutation() *SendLimiterMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *SendLimiterUpdate) ClearWorkspace() *SendLimiterUpdate {
	_u.mutation.ClearWorkspace()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SendLimiterUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SendLimiterUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SendLimiterUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SendLimiterUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SendLimiterUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sendlimiter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SendLimiterUpdate) check() error {
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SendLimiter.workspace"`)
	}
	if _u.mutation.IntegrationCleared() && len(_u.mutation.IntegrationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SendLimiter.integration"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SendLimiterUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SendLimiterUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SendLimiterUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sendlimiter.Table, sendlimiter.Columns, sqlgraph.NewFieldSpec(sendlimiter.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sendlimiter.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SecondFill(); ok {
		_spec.SetField(sendlimiter.FieldSecondFill, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSecondFill(); ok {
		_spec.AddField(sendlimiter.FieldSecondFill, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DayFill(); ok {
		_spec.SetField(sendlimiter.FieldDayFill, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDayFill(); ok {
		_spec.AddField(sendlimiter.FieldDayFill, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefilledAt(); ok {
		_spec.SetField(sendlimiter.FieldRefilledAt, field.TypeTime, value)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sendlimiter.WorkspaceTable,
			Columns: []string{sendlimiter.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sendlimiter.WorkspaceTable,
			Columns: []string{sendlimiter.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sendlimiter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SendLimiterUpdateOne is the builder for updating a single SendLimiter entity.
type SendLimiterUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *SendLimiterMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SendLimiterUpdateOne) SetUpdatedAt(v time.Time) *SendLimiterUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetWorkspaceID sets the "workspace_id" field.
func (_u *SendLimiterUpdateOne) SetWorkspaceID(v int64) *SendLimiterUpdateOne {
	_u.mutation.SetWorkspaceID(v)
	return _u
}

// SetNillableWorkspaceID sets the "workspace_id" field if the given value is not nil.
func (_u *SendLimiterUpdateOne) SetNillableWorkspaceID(v *int64) *SendLimiterUpdateOne {
	if v != nil {
		_u.SetWorkspaceID(*v)
	}
	return _u
}

// SetSecondFill sets the "second_fill" field.
func (_u *SendLimiterUpdateOne) SetSecondFill(v float64) *SendLimiterUpdateOne {
	_u.mutation.ResetSecondFill()
	_u.mutation.SetSecondFill(v)
	return _u
}

// SetNillableSecondFill sets the "second_fill" field if the given value is not nil.
func (_u *SendLimiterUpdateOne) SetNillableSecondFill(v *float64) *SendLimiterUpdateOne {
	if v != nil {
		_u.SetSecondFill(*v)
	}
	return _u
}

// AddSecondFill adds value to the "second_fill" field.
func (_u *SendLimiterUpdateOne) AddSecondFill(v float64) *SendLimiterUpdateOne {
	_u.mutation.AddSecondFill(v)
	return _u
}

// SetDayFill sets the "day_fill" field.
func (_u *SendLimiterUpdateOne) SetDayFill(v float64) *SendLimiterUpdateOne {
	_u.mutation.ResetDayFill()
	_u.mutation.SetDayFill(v)
	return _u
}

// SetNillableDayFill sets the "day_fill" field if the given value is not nil.
func (_u *SendLimiterUpdateOne) SetNillableDayFill(v *float64) *SendLimiterUpdateOne {
	if v != nil {
		_u.SetDayFill(*v)
	}
	return _u
}

// AddDayFill adds value to the "day_fill" field.
func (_u *SendLimiterUpdateOne) AddDayFill(v float64) *SendLimiterUpdateOne {
	_u.mutation.AddDayFill(v)
	return _u
}

// SetRefilledAt sets the "refilled_at" field.
func (_u *SendLimiterUpdateOne) SetRefilledAt(v time.Time) *SendLimiterUpdateOne {
	_u.mutation.SetRefilledAt(v)
	return _u
}

// SetNillableRefilledAt sets the "refilled_at" field if the given value is not nil.
func (_u *SendLimiterUpdateOne) SetNillableRefilledAt(v *time.Time) *SendLimiterUpdateOne {
	if v != nil {
		_u.SetRefilledAt(*v)
	}
	return _u
}

// SetWorkspace sets the "workspace" edge to the Workspace entity.
func (_u *SendLimiterUpdateOne) SetWorkspace(v *Workspace) *SendLimiterUpdateOne {
	return _u.SetWorkspaceID(v.ID)
}

// Mutation returns the SendLimiterMutation object of the builder.
func (_u *SendLimiterUpdateOne) Mutation() *SendLimiterMutation {
	return _u.mutation
}

// ClearWorkspace clears the "workspace" edge to the Workspace entity.
func (_u *SendLimiterUpdateOne) ClearWorkspace() *SendLimiterUpdateOne {
	_u.mutation.ClearWorkspace()
	return _u
}

// Where appends a list predicates to the SendLimiterUpdate builder.
func (_u *SendLimiterUpdateOne) Where(ps ...predicate.SendLimiter) *SendLimiterUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SendLimiterUpdateOne) Select(field string, fields ...string) *SendLimiterUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SendLimiter entity.
func (_u *SendLimiterUpdateOne) Save(ctx context.Context) (*SendLimiter, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SendLimiterUpdateOne) SaveX(ctx context.Context) *SendLimiter {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SendLimiterUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SendLimiterUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SendLimiterUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := sendlimiter.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SendLimiterUpdateOne) check() error {
	if _u.mutation.WorkspaceCleared() && len(_u.mutation.WorkspaceIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SendLimiter.workspace"`)
	}
	if _u.mutation.IntegrationCleared() && len(_u.mutation.IntegrationIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SendLimiter.integration"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *SendLimiterUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *SendLimiterUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *SendLimiterUpdateOne) sqlSave(ctx context.Context) (_node *SendLimiter, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(sendlimiter.Table, sendlimiter.Columns, sqlgraph.NewFieldSpec(sendlimiter.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SendLimiter.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, sendlimiter.FieldID)
		for _, f := range fields {
			if !sendlimiter.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != sendlimiter.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(sendlimiter.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.SecondFill(); ok {
		_spec.SetField(sendlimiter.FieldSecondFill, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedSecondFill(); ok {
		_spec.AddField(sendlimiter.FieldSecondFill, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DayFill(); ok {
		_spec.SetField(sendlimiter.FieldDayFill, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDayFill(); ok {
		_spec.AddField(sendlimiter.FieldDayFill, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefilledAt(); ok {
		_spec.SetField(sendlimiter.FieldRefilledAt, field.TypeTime, value)
	}
	if _u.mutation.WorkspaceCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sendlimiter.WorkspaceTable,
			Columns: []string{sendlimiter.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WorkspaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   sendlimiter.WorkspaceTable,
			Columns: []string{sendlimiter.WorkspaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &SendLimiter{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{sendlimiter.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
