// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/mokevnin/1mail/ent/apitoken"
	"github.com/mokevnin/1mail/ent/contact"
	"github.com/mokevnin/1mail/ent/event"
	"github.com/mokevnin/1mail/ent/integration"
	"github.com/mokevnin/1mail/ent/predicate"
	"github.com/mokevnin/1mail/ent/segment"
	"github.com/mokevnin/1mail/ent/trackingprofile"
	"github.com/mokevnin/1mail/ent/trackingvisitor"
	"github.com/mokevnin/1mail/ent/user"
	"github.com/mokevnin/1mail/ent/workspace"
)

// WorkspaceUpdate is the builder for updating Workspace entities.
type WorkspaceUpdate struct {
	config
	hooks    []Hook
	mutation *WorkspaceMutation
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (_u *WorkspaceUpdate) Where(ps ...predicate.Workspace) *WorkspaceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *WorkspaceUpdate) SetName(v string) *WorkspaceUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableName(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *WorkspaceUpdate) SetSlug(v string) *WorkspaceUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableSlug(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetCollectKey sets the "collect_key" field.
func (_u *WorkspaceUpdate) SetCollectKey(v string) *WorkspaceUpdate {
	_u.mutation.SetCollectKey(v)
	return _u
}

// SetNillableCollectKey sets the "collect_key" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableCollectKey(v *string) *WorkspaceUpdate {
	if v != nil {
		_u.SetCollectKey(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WorkspaceUpdate) SetUserID(v int64) *WorkspaceUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WorkspaceUpdate) SetNillableUserID(v *int64) *WorkspaceUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *WorkspaceUpdate) ClearUserID() *WorkspaceUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceUpdate) SetUpdatedAt(v time.Time) *WorkspaceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddContactIDs adds the "contacts" edge to the Contact entity by IDs.
func (_u *WorkspaceUpdate) AddContactIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.AddContactIDs(ids...)
	return _u
}

// AddContacts adds the "contacts" edges to the Contact entity.
func (_u *WorkspaceUpdate) AddContacts(v ...*Contact) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContactIDs(ids...)
}

// AddSegmentIDs adds the "segments" edge to the Segment entity by IDs.
func (_u *WorkspaceUpdate) AddSegmentIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.AddSegmentIDs(ids...)
	return _u
}

// AddSegments adds the "segments" edges to the Segment entity.
func (_u *WorkspaceUpdate) AddSegments(v ...*Segment) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSegmentIDs(ids...)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *WorkspaceUpdate) AddEventIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *WorkspaceUpdate) AddEvents(v ...*Event) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// AddTrackingProfileIDs adds the "tracking_profiles" edge to the TrackingProfile entity by IDs.
func (_u *WorkspaceUpdate) AddTrackingProfileIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.AddTrackingProfileIDs(ids...)
	return _u
}

// AddTrackingProfiles adds the "tracking_profiles" edges to the TrackingProfile entity.
func (_u *WorkspaceUpdate) AddTrackingProfiles(v ...*TrackingProfile) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTrackingProfileIDs(ids...)
}

// AddTrackingVisitorIDs adds the "tracking_visitors" edge to the TrackingVisitor entity by IDs.
func (_u *WorkspaceUpdate) AddTrackingVisitorIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.AddTrackingVisitorIDs(ids...)
	return _u
}

// AddTrackingVisitors adds the "tracking_visitors" edges to the TrackingVisitor entity.
func (_u *WorkspaceUpdate) AddTrackingVisitors(v ...*TrackingVisitor) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTrackingVisitorIDs(ids...)
}

// AddAPITokenIDs adds the "api_tokens" edge to the ApiToken entity by IDs.
func (_u *WorkspaceUpdate) AddAPITokenIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.AddAPITokenIDs(ids...)
	return _u
}

// AddAPITokens adds the "api_tokens" edges to the ApiToken entity.
func (_u *WorkspaceUpdate) AddAPITokens(v ...*ApiToken) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPITokenIDs(ids...)
}

// AddIntegrationIDs adds the "integrations" edge to the Integration entity by IDs.
func (_u *WorkspaceUpdate) AddIntegrationIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.AddIntegrationIDs(ids...)
	return _u
}

// AddIntegrations adds the "integrations" edges to the Integration entity.
func (_u *WorkspaceUpdate) AddIntegrations(v ...*Integration) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIntegrationIDs(ids...)
}

// SetUser sets the "user" edge to the User entity.
func (_u *WorkspaceUpdate) SetUser(v *User) *WorkspaceUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the WorkspaceMutation object of the builder.
func (_u *WorkspaceUpdate) Mutation() *WorkspaceMutation {
	return _u.mutation
}

// ClearContacts clears all "contacts" edges to the Contact entity.
func (_u *WorkspaceUpdate) ClearContacts() *WorkspaceUpdate {
	_u.mutation.ClearContacts()
	return _u
}

// RemoveContactIDs removes the "contacts" edge to Contact entities by IDs.
func (_u *WorkspaceUpdate) RemoveContactIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.RemoveContactIDs(ids...)
	return _u
}

// RemoveContacts removes "contacts" edges to Contact entities.
func (_u *WorkspaceUpdate) RemoveContacts(v ...*Contact) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContactIDs(ids...)
}

// ClearSegments clears all "segments" edges to the Segment entity.
func (_u *WorkspaceUpdate) ClearSegments() *WorkspaceUpdate {
	_u.mutation.ClearSegments()
	return _u
}

// RemoveSegmentIDs removes the "segments" edge to Segment entities by IDs.
func (_u *WorkspaceUpdate) RemoveSegmentIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.RemoveSegmentIDs(ids...)
	return _u
}

// RemoveSegments removes "segments" edges to Segment entities.
func (_u *WorkspaceUpdate) RemoveSegments(v ...*Segment) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSegmentIDs(ids...)
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *WorkspaceUpdate) ClearEvents() *WorkspaceUpdate {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *WorkspaceUpdate) RemoveEventIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *WorkspaceUpdate) RemoveEvents(v ...*Event) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// ClearTrackingProfiles clears all "tracking_profiles" edges to the TrackingProfile entity.
func (_u *WorkspaceUpdate) ClearTrackingProfiles() *WorkspaceUpdate {
	_u.mutation.ClearTrackingProfiles()
	return _u
}

// RemoveTrackingProfileIDs removes the "tracking_profiles" edge to TrackingProfile entities by IDs.
func (_u *WorkspaceUpdate) RemoveTrackingProfileIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.RemoveTrackingProfileIDs(ids...)
	return _u
}

// RemoveTrackingProfiles removes "tracking_profiles" edges to TrackingProfile entities.
func (_u *WorkspaceUpdate) RemoveTrackingProfiles(v ...*TrackingProfile) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTrackingProfileIDs(ids...)
}

// ClearTrackingVisitors clears all "tracking_visitors" edges to the TrackingVisitor entity.
func (_u *WorkspaceUpdate) ClearTrackingVisitors() *WorkspaceUpdate {
	_u.mutation.ClearTrackingVisitors()
	return _u
}

// RemoveTrackingVisitorIDs removes the "tracking_visitors" edge to TrackingVisitor entities by IDs.
func (_u *WorkspaceUpdate) RemoveTrackingVisitorIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.RemoveTrackingVisitorIDs(ids...)
	return _u
}

// RemoveTrackingVisitors removes "tracking_visitors" edges to TrackingVisitor entities.
func (_u *WorkspaceUpdate) RemoveTrackingVisitors(v ...*TrackingVisitor) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTrackingVisitorIDs(ids...)
}

// ClearAPITokens clears all "api_tokens" edges to the ApiToken entity.
func (_u *WorkspaceUpdate) ClearAPITokens() *WorkspaceUpdate {
	_u.mutation.ClearAPITokens()
	return _u
}

// RemoveAPITokenIDs removes the "api_tokens" edge to ApiToken entities by IDs.
func (_u *WorkspaceUpdate) RemoveAPITokenIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.RemoveAPITokenIDs(ids...)
	return _u
}

// RemoveAPITokens removes "api_tokens" edges to ApiToken entities.
func (_u *WorkspaceUpdate) RemoveAPITokens(v ...*ApiToken) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPITokenIDs(ids...)
}

// ClearIntegrations clears all "integrations" edges to the Integration entity.
func (_u *WorkspaceUpdate) ClearIntegrations() *WorkspaceUpdate {
	_u.mutation.ClearIntegrations()
	return _u
}

// RemoveIntegrationIDs removes the "integrations" edge to Integration entities by IDs.
func (_u *WorkspaceUpdate) RemoveIntegrationIDs(ids ...int64) *WorkspaceUpdate {
	_u.mutation.RemoveIntegrationIDs(ids...)
	return _u
}

// RemoveIntegrations removes "integrations" edges to Integration entities.
func (_u *WorkspaceUpdate) RemoveIntegrations(v ...*Integration) *WorkspaceUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIntegrationIDs(ids...)
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WorkspaceUpdate) ClearUser() *WorkspaceUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WorkspaceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WorkspaceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkspaceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workspace.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := workspace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workspace.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := workspace.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Workspace.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CollectKey(); ok {
		if err := workspace.CollectKeyValidator(v); err != nil {
			return &ValidationError{Name: "collect_key", err: fmt.Errorf(`ent: validator failed for field "Workspace.collect_key": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkspaceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(workspace.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.CollectKey(); ok {
		_spec.SetField(workspace.FieldCollectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.ContactsTable,
			Columns: []string{workspace.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContactsIDs(); len(nodes) > 0 && !_u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.ContactsTable,
			Columns: []string{workspace.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContactsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.ContactsTable,
			Columns: []string{workspace.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SegmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.SegmentsTable,
			Columns: []string{workspace.SegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(segment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSegmentsIDs(); len(nodes) > 0 && !_u.mutation.SegmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.SegmentsTable,
			Columns: []string{workspace.SegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(segment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SegmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.SegmentsTable,
			Columns: []string{workspace.SegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(segment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.EventsTable,
			Columns: []string{workspace.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.EventsTable,
			Columns: []string{workspace.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.EventsTable,
			Columns: []string{workspace.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TrackingProfilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TrackingProfilesTable,
			Columns: []string{workspace.TrackingProfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingprofile.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTrackingProfilesIDs(); len(nodes) > 0 && !_u.mutation.TrackingProfilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TrackingProfilesTable,
			Columns: []string{workspace.TrackingProfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingprofile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TrackingProfilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TrackingProfilesTable,
			Columns: []string{workspace.TrackingProfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingprofile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TrackingVisitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TrackingVisitorsTable,
			Columns: []string{workspace.TrackingVisitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingvisitor.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTrackingVisitorsIDs(); len(nodes) > 0 && !_u.mutation.TrackingVisitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TrackingVisitorsTable,
			Columns: []string{workspace.TrackingVisitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingvisitor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TrackingVisitorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TrackingVisitorsTable,
			Columns: []string{workspace.TrackingVisitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingvisitor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APITokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.APITokensTable,
			Columns: []string{workspace.APITokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPITokensIDs(); len(nodes) > 0 && !_u.mutation.APITokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.APITokensTable,
			Columns: []string{workspace.APITokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APITokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.APITokensTable,
			Columns: []string{workspace.APITokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IntegrationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.IntegrationsTable,
			Columns: []string{workspace.IntegrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIntegrationsIDs(); len(nodes) > 0 && !_u.mutation.IntegrationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.IntegrationsTable,
			Columns: []string{workspace.IntegrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IntegrationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.IntegrationsTable,
			Columns: []string{workspace.IntegrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.UserTable,
			Columns: []string{workspace.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.UserTable,
			Columns: []string{workspace.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WorkspaceUpdateOne is the builder for updating a single Workspace entity.
type WorkspaceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WorkspaceMutation
}

// SetName sets the "name" field.
func (_u *WorkspaceUpdateOne) SetName(v string) *WorkspaceUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableName(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *WorkspaceUpdateOne) SetSlug(v string) *WorkspaceUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableSlug(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetCollectKey sets the "collect_key" field.
func (_u *WorkspaceUpdateOne) SetCollectKey(v string) *WorkspaceUpdateOne {
	_u.mutation.SetCollectKey(v)
	return _u
}

// SetNillableCollectKey sets the "collect_key" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableCollectKey(v *string) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetCollectKey(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *WorkspaceUpdateOne) SetUserID(v int64) *WorkspaceUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *WorkspaceUpdateOne) SetNillableUserID(v *int64) *WorkspaceUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *WorkspaceUpdateOne) ClearUserID() *WorkspaceUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WorkspaceUpdateOne) SetUpdatedAt(v time.Time) *WorkspaceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddContactIDs adds the "contacts" edge to the Contact entity by IDs.
func (_u *WorkspaceUpdateOne) AddContactIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.AddContactIDs(ids...)
	return _u
}

// AddContacts adds the "contacts" edges to the Contact entity.
func (_u *WorkspaceUpdateOne) AddContacts(v ...*Contact) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContactIDs(ids...)
}

// AddSegmentIDs adds the "segments" edge to the Segment entity by IDs.
func (_u *WorkspaceUpdateOne) AddSegmentIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.AddSegmentIDs(ids...)
	return _u
}

// AddSegments adds the "segments" edges to the Segment entity.
func (_u *WorkspaceUpdateOne) AddSegments(v ...*Segment) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSegmentIDs(ids...)
}

// AddEventIDs adds the "events" edge to the Event entity by IDs.
func (_u *WorkspaceUpdateOne) AddEventIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.AddEventIDs(ids...)
	return _u
}

// AddEvents adds the "events" edges to the Event entity.
func (_u *WorkspaceUpdateOne) AddEvents(v ...*Event) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEventIDs(ids...)
}

// AddTrackingProfileIDs adds the "tracking_profiles" edge to the TrackingProfile entity by IDs.
func (_u *WorkspaceUpdateOne) AddTrackingProfileIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.AddTrackingProfileIDs(ids...)
	return _u
}

// AddTrackingProfiles adds the "tracking_profiles" edges to the TrackingProfile entity.
func (_u *WorkspaceUpdateOne) AddTrackingProfiles(v ...*TrackingProfile) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTrackingProfileIDs(ids...)
}

// AddTrackingVisitorIDs adds the "tracking_visitors" edge to the TrackingVisitor entity by IDs.
func (_u *WorkspaceUpdateOne) AddTrackingVisitorIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.AddTrackingVisitorIDs(ids...)
	return _u
}

// AddTrackingVisitors adds the "tracking_visitors" edges to the TrackingVisitor entity.
func (_u *WorkspaceUpdateOne) AddTrackingVisitors(v ...*TrackingVisitor) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTrackingVisitorIDs(ids...)
}

// AddAPITokenIDs adds the "api_tokens" edge to the ApiToken entity by IDs.
func (_u *WorkspaceUpdateOne) AddAPITokenIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.AddAPITokenIDs(ids...)
	return _u
}

// AddAPITokens adds the "api_tokens" edges to the ApiToken entity.
func (_u *WorkspaceUpdateOne) AddAPITokens(v ...*ApiToken) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAPITokenIDs(ids...)
}

// AddIntegrationIDs adds the "integrations" edge to the Integration entity by IDs.
func (_u *WorkspaceUpdateOne) AddIntegrationIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.AddIntegrationIDs(ids...)
	return _u
}

// AddIntegrations adds the "integrations" edges to the Integration entity.
func (_u *WorkspaceUpdateOne) AddIntegrations(v ...*Integration) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddIntegrationIDs(ids...)
}

// SetUser sets the "user" edge to the User entity.
func (_u *WorkspaceUpdateOne) SetUser(v *User) *WorkspaceUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the WorkspaceMutation object of the builder.
func (_u *WorkspaceUpdateOne) Mutation() *WorkspaceMutation {
	return _u.mutation
}

// ClearContacts clears all "contacts" edges to the Contact entity.
func (_u *WorkspaceUpdateOne) ClearContacts() *WorkspaceUpdateOne {
	_u.mutation.ClearContacts()
	return _u
}

// RemoveContactIDs removes the "contacts" edge to Contact entities by IDs.
func (_u *WorkspaceUpdateOne) RemoveContactIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.RemoveContactIDs(ids...)
	return _u
}

// RemoveContacts removes "contacts" edges to Contact entities.
func (_u *WorkspaceUpdateOne) RemoveContacts(v ...*Contact) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContactIDs(ids...)
}

// ClearSegments clears all "segments" edges to the Segment entity.
func (_u *WorkspaceUpdateOne) ClearSegments() *WorkspaceUpdateOne {
	_u.mutation.ClearSegments()
	return _u
}

// RemoveSegmentIDs removes the "segments" edge to Segment entities by IDs.
func (_u *WorkspaceUpdateOne) RemoveSegmentIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.RemoveSegmentIDs(ids...)
	return _u
}

// RemoveSegments removes "segments" edges to Segment entities.
func (_u *WorkspaceUpdateOne) RemoveSegments(v ...*Segment) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSegmentIDs(ids...)
}

// ClearEvents clears all "events" edges to the Event entity.
func (_u *WorkspaceUpdateOne) ClearEvents() *WorkspaceUpdateOne {
	_u.mutation.ClearEvents()
	return _u
}

// RemoveEventIDs removes the "events" edge to Event entities by IDs.
func (_u *WorkspaceUpdateOne) RemoveEventIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.RemoveEventIDs(ids...)
	return _u
}

// RemoveEvents removes "events" edges to Event entities.
func (_u *WorkspaceUpdateOne) RemoveEvents(v ...*Event) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEventIDs(ids...)
}

// ClearTrackingProfiles clears all "tracking_profiles" edges to the TrackingProfile entity.
func (_u *WorkspaceUpdateOne) ClearTrackingProfiles() *WorkspaceUpdateOne {
	_u.mutation.ClearTrackingProfiles()
	return _u
}

// RemoveTrackingProfileIDs removes the "tracking_profiles" edge to TrackingProfile entities by IDs.
func (_u *WorkspaceUpdateOne) RemoveTrackingProfileIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.RemoveTrackingProfileIDs(ids...)
	return _u
}

// RemoveTrackingProfiles removes "tracking_profiles" edges to TrackingProfile entities.
func (_u *WorkspaceUpdateOne) RemoveTrackingProfiles(v ...*TrackingProfile) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTrackingProfileIDs(ids...)
}

// ClearTrackingVisitors clears all "tracking_visitors" edges to the TrackingVisitor entity.
func (_u *WorkspaceUpdateOne) ClearTrackingVisitors() *WorkspaceUpdateOne {
	_u.mutation.ClearTrackingVisitors()
	return _u
}

// RemoveTrackingVisitorIDs removes the "tracking_visitors" edge to TrackingVisitor entities by IDs.
func (_u *WorkspaceUpdateOne) RemoveTrackingVisitorIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.RemoveTrackingVisitorIDs(ids...)
	return _u
}

// RemoveTrackingVisitors removes "tracking_visitors" edges to TrackingVisitor entities.
func (_u *WorkspaceUpdateOne) RemoveTrackingVisitors(v ...*TrackingVisitor) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTrackingVisitorIDs(ids...)
}

// ClearAPITokens clears all "api_tokens" edges to the ApiToken entity.
func (_u *WorkspaceUpdateOne) ClearAPITokens() *WorkspaceUpdateOne {
	_u.mutation.ClearAPITokens()
	return _u
}

// RemoveAPITokenIDs removes the "api_tokens" edge to ApiToken entities by IDs.
func (_u *WorkspaceUpdateOne) RemoveAPITokenIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.RemoveAPITokenIDs(ids...)
	return _u
}

// RemoveAPITokens removes "api_tokens" edges to ApiToken entities.
func (_u *WorkspaceUpdateOne) RemoveAPITokens(v ...*ApiToken) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAPITokenIDs(ids...)
}

// ClearIntegrations clears all "integrations" edges to the Integration entity.
func (_u *WorkspaceUpdateOne) ClearIntegrations() *WorkspaceUpdateOne {
	_u.mutation.ClearIntegrations()
	return _u
}

// RemoveIntegrationIDs removes the "integrations" edge to Integration entities by IDs.
func (_u *WorkspaceUpdateOne) RemoveIntegrationIDs(ids ...int64) *WorkspaceUpdateOne {
	_u.mutation.RemoveIntegrationIDs(ids...)
	return _u
}

// RemoveIntegrations removes "integrations" edges to Integration entities.
func (_u *WorkspaceUpdateOne) RemoveIntegrations(v ...*Integration) *WorkspaceUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveIntegrationIDs(ids...)
}

// ClearUser clears the "user" edge to the User entity.
func (_u *WorkspaceUpdateOne) ClearUser() *WorkspaceUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the WorkspaceUpdate builder.
func (_u *WorkspaceUpdateOne) Where(ps ...predicate.Workspace) *WorkspaceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WorkspaceUpdateOne) Select(field string, fields ...string) *WorkspaceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Workspace entity.
func (_u *WorkspaceUpdateOne) Save(ctx context.Context) (*Workspace, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WorkspaceUpdateOne) SaveX(ctx context.Context) *Workspace {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WorkspaceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WorkspaceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WorkspaceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := workspace.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WorkspaceUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := workspace.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Workspace.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := workspace.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Workspace.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.CollectKey(); ok {
		if err := workspace.CollectKeyValidator(v); err != nil {
			return &ValidationError{Name: "collect_key", err: fmt.Errorf(`ent: validator failed for field "Workspace.collect_key": %w`, err)}
		}
	}
	return nil
}

func (_u *WorkspaceUpdateOne) sqlSave(ctx context.Context) (_node *Workspace, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(workspace.Table, workspace.Columns, sqlgraph.NewFieldSpec(workspace.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Workspace.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, workspace.FieldID)
		for _, f := range fields {
			if !workspace.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != workspace.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(workspace.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(workspace.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.CollectKey(); ok {
		_spec.SetField(workspace.FieldCollectKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(workspace.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.ContactsTable,
			Columns: []string{workspace.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContactsIDs(); len(nodes) > 0 && !_u.mutation.ContactsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.ContactsTable,
			Columns: []string{workspace.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContactsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.ContactsTable,
			Columns: []string{workspace.ContactsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(contact.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.SegmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.SegmentsTable,
			Columns: []string{workspace.SegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(segment.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSegmentsIDs(); len(nodes) > 0 && !_u.mutation.SegmentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.SegmentsTable,
			Columns: []string{workspace.SegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(segment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SegmentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.SegmentsTable,
			Columns: []string{workspace.SegmentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(segment.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.EventsTable,
			Columns: []string{workspace.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEventsIDs(); len(nodes) > 0 && !_u.mutation.EventsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.EventsTable,
			Columns: []string{workspace.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EventsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.EventsTable,
			Columns: []string{workspace.EventsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TrackingProfilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TrackingProfilesTable,
			Columns: []string{workspace.TrackingProfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingprofile.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTrackingProfilesIDs(); len(nodes) > 0 && !_u.mutation.TrackingProfilesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TrackingProfilesTable,
			Columns: []string{workspace.TrackingProfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingprofile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TrackingProfilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TrackingProfilesTable,
			Columns: []string{workspace.TrackingProfilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingprofile.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TrackingVisitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TrackingVisitorsTable,
			Columns: []string{workspace.TrackingVisitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingvisitor.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTrackingVisitorsIDs(); len(nodes) > 0 && !_u.mutation.TrackingVisitorsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TrackingVisitorsTable,
			Columns: []string{workspace.TrackingVisitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingvisitor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TrackingVisitorsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.TrackingVisitorsTable,
			Columns: []string{workspace.TrackingVisitorsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(trackingvisitor.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.APITokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.APITokensTable,
			Columns: []string{workspace.APITokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAPITokensIDs(); len(nodes) > 0 && !_u.mutation.APITokensCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.APITokensTable,
			Columns: []string{workspace.APITokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.APITokensIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.APITokensTable,
			Columns: []string{workspace.APITokensColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apitoken.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.IntegrationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.IntegrationsTable,
			Columns: []string{workspace.IntegrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedIntegrationsIDs(); len(nodes) > 0 && !_u.mutation.IntegrationsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.IntegrationsTable,
			Columns: []string{workspace.IntegrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.IntegrationsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   workspace.IntegrationsTable,
			Columns: []string{workspace.IntegrationsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(integration.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.UserTable,
			Columns: []string{workspace.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   workspace.UserTable,
			Columns: []string{workspace.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Workspace{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{workspace.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
