// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/mokevnin/1mail/ent/workspace"
)

// Workspace is the model entity for the Workspace schema.
type Workspace struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// CollectKey holds the value of the "collect_key" field.
	CollectKey string `json:"-"`
	// IngestKey holds the value of the "ingest_key" field.
	IngestKey string `json:"-"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WorkspaceQuery when eager-loading is set.
	Edges        WorkspaceEdges `json:"edges"`
	selectValues sql.SelectValues
}

// WorkspaceEdges holds the relations/edges for other nodes in the graph.
type WorkspaceEdges struct {
	// Contacts holds the value of the contacts edge.
	Contacts []*Contact `json:"contacts,omitempty"`
	// CustomFields holds the value of the custom_fields edge.
	CustomFields []*CustomField `json:"custom_fields,omitempty"`
	// Segments holds the value of the segments edge.
	Segments []*Segment `json:"segments,omitempty"`
	// Events holds the value of the events edge.
	Events []*Event `json:"events,omitempty"`
	// Visitors holds the value of the visitors edge.
	Visitors []*Visitor `json:"visitors,omitempty"`
	// APITokens holds the value of the api_tokens edge.
	APITokens []*ApiToken `json:"api_tokens,omitempty"`
	// Integrations holds the value of the integrations edge.
	Integrations []*Integration `json:"integrations,omitempty"`
	// SendingDomains holds the value of the sending_domains edge.
	SendingDomains []*SendingDomain `json:"sending_domains,omitempty"`
	// Broadcasts holds the value of the broadcasts edge.
	Broadcasts []*Broadcast `json:"broadcasts,omitempty"`
	// BroadcastRecipients holds the value of the broadcast_recipients edge.
	BroadcastRecipients []*BroadcastRecipient `json:"broadcast_recipients,omitempty"`
	// EmailTemplates holds the value of the email_templates edge.
	EmailTemplates []*EmailTemplate `json:"email_templates,omitempty"`
	// Automations holds the value of the automations edge.
	Automations []*Automation `json:"automations,omitempty"`
	// AutomationRuns holds the value of the automation_runs edge.
	AutomationRuns []*AutomationRun `json:"automation_runs,omitempty"`
	// WebhookEndpoints holds the value of the webhook_endpoints edge.
	WebhookEndpoints []*WebhookEndpoint `json:"webhook_endpoints,omitempty"`
	// Suppressions holds the value of the suppressions edge.
	Suppressions []*Suppression `json:"suppressions,omitempty"`
	// Unsubscribes holds the value of the unsubscribes edge.
	Unsubscribes []*Unsubscribe `json:"unsubscribes,omitempty"`
	// TransactionalEmails holds the value of the transactional_emails edge.
	TransactionalEmails []*TransactionalEmail `json:"transactional_emails,omitempty"`
	// Memberships holds the value of the memberships edge.
	Memberships []*Membership `json:"memberships,omitempty"`
	// Invitations holds the value of the invitations edge.
	Invitations []*Invitation `json:"invitations,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [19]bool
}

// ContactsOrErr returns the Contacts value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) ContactsOrErr() ([]*Contact, error) {
	if e.loadedTypes[0] {
		return e.Contacts, nil
	}
	return nil, &NotLoadedError{edge: "contacts"}
}

// CustomFieldsOrErr returns the CustomFields value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) CustomFieldsOrErr() ([]*CustomField, error) {
	if e.loadedTypes[1] {
		return e.CustomFields, nil
	}
	return nil, &NotLoadedError{edge: "custom_fields"}
}

// SegmentsOrErr returns the Segments value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) SegmentsOrErr() ([]*Segment, error) {
	if e.loadedTypes[2] {
		return e.Segments, nil
	}
	return nil, &NotLoadedError{edge: "segments"}
}

// EventsOrErr returns the Events value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) EventsOrErr() ([]*Event, error) {
	if e.loadedTypes[3] {
		return e.Events, nil
	}
	return nil, &NotLoadedError{edge: "events"}
}

// VisitorsOrErr returns the Visitors value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) VisitorsOrErr() ([]*Visitor, error) {
	if e.loadedTypes[4] {
		return e.Visitors, nil
	}
	return nil, &NotLoadedError{edge: "visitors"}
}

// APITokensOrErr returns the APITokens value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) APITokensOrErr() ([]*ApiToken, error) {
	if e.loadedTypes[5] {
		return e.APITokens, nil
	}
	return nil, &NotLoadedError{edge: "api_tokens"}
}

// IntegrationsOrErr returns the Integrations value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) IntegrationsOrErr() ([]*Integration, error) {
	if e.loadedTypes[6] {
		return e.Integrations, nil
	}
	return nil, &NotLoadedError{edge: "integrations"}
}

// SendingDomainsOrErr returns the SendingDomains value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) SendingDomainsOrErr() ([]*SendingDomain, error) {
	if e.loadedTypes[7] {
		return e.SendingDomains, nil
	}
	return nil, &NotLoadedError{edge: "sending_domains"}
}

// BroadcastsOrErr returns the Broadcasts value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) BroadcastsOrErr() ([]*Broadcast, error) {
	if e.loadedTypes[8] {
		return e.Broadcasts, nil
	}
	return nil, &NotLoadedError{edge: "broadcasts"}
}

// BroadcastRecipientsOrErr returns the BroadcastRecipients value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) BroadcastRecipientsOrErr() ([]*BroadcastRecipient, error) {
	if e.loadedTypes[9] {
		return e.BroadcastRecipients, nil
	}
	return nil, &NotLoadedError{edge: "broadcast_recipients"}
}

// EmailTemplatesOrErr returns the EmailTemplates value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) EmailTemplatesOrErr() ([]*EmailTemplate, error) {
	if e.loadedTypes[10] {
		return e.EmailTemplates, nil
	}
	return nil, &NotLoadedError{edge: "email_templates"}
}

// AutomationsOrErr returns the Automations value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) AutomationsOrErr() ([]*Automation, error) {
	if e.loadedTypes[11] {
		return e.Automations, nil
	}
	return nil, &NotLoadedError{edge: "automations"}
}

// AutomationRunsOrErr returns the AutomationRuns value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) AutomationRunsOrErr() ([]*AutomationRun, error) {
	if e.loadedTypes[12] {
		return e.AutomationRuns, nil
	}
	return nil, &NotLoadedError{edge: "automation_runs"}
}

// WebhookEndpointsOrErr returns the WebhookEndpoints value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) WebhookEndpointsOrErr() ([]*WebhookEndpoint, error) {
	if e.loadedTypes[13] {
		return e.WebhookEndpoints, nil
	}
	return nil, &NotLoadedError{edge: "webhook_endpoints"}
}

// SuppressionsOrErr returns the Suppressions value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) SuppressionsOrErr() ([]*Suppression, error) {
	if e.loadedTypes[14] {
		return e.Suppressions, nil
	}
	return nil, &NotLoadedError{edge: "suppressions"}
}

// UnsubscribesOrErr returns the Unsubscribes value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) UnsubscribesOrErr() ([]*Unsubscribe, error) {
	if e.loadedTypes[15] {
		return e.Unsubscribes, nil
	}
	return nil, &NotLoadedError{edge: "unsubscribes"}
}

// TransactionalEmailsOrErr returns the TransactionalEmails value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) TransactionalEmailsOrErr() ([]*TransactionalEmail, error) {
	if e.loadedTypes[16] {
		return e.TransactionalEmails, nil
	}
	return nil, &NotLoadedError{edge: "transactional_emails"}
}

// MembershipsOrErr returns the Memberships value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) MembershipsOrErr() ([]*Membership, error) {
	if e.loadedTypes[17] {
		return e.Memberships, nil
	}
	return nil, &NotLoadedError{edge: "memberships"}
}

// InvitationsOrErr returns the Invitations value or an error if the edge
// was not loaded in eager-loading.
func (e WorkspaceEdges) InvitationsOrErr() ([]*Invitation, error) {
	if e.loadedTypes[18] {
		return e.Invitations, nil
	}
	return nil, &NotLoadedError{edge: "invitations"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Workspace) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case workspace.FieldID:
			values[i] = new(sql.NullInt64)
		case workspace.FieldName, workspace.FieldSlug, workspace.FieldCollectKey, workspace.FieldIngestKey:
			values[i] = new(sql.NullString)
		case workspace.FieldCreatedAt, workspace.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Workspace fields.
func (_m *Workspace) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case workspace.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case workspace.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case workspace.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case workspace.FieldCollectKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field collect_key", values[i])
			} else if value.Valid {
				_m.CollectKey = value.String
			}
		case workspace.FieldIngestKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ingest_key", values[i])
			} else if value.Valid {
				_m.IngestKey = value.String
			}
		case workspace.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case workspace.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Workspace.
// This includes values selected through modifiers, order, etc.
func (_m *Workspace) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryContacts queries the "contacts" edge of the Workspace entity.
func (_m *Workspace) QueryContacts() *ContactQuery {
	return NewWorkspaceClient(_m.config).QueryContacts(_m)
}

// QueryCustomFields queries the "custom_fields" edge of the Workspace entity.
func (_m *Workspace) QueryCustomFields() *CustomFieldQuery {
	return NewWorkspaceClient(_m.config).QueryCustomFields(_m)
}

// QuerySegments queries the "segments" edge of the Workspace entity.
func (_m *Workspace) QuerySegments() *SegmentQuery {
	return NewWorkspaceClient(_m.config).QuerySegments(_m)
}

// QueryEvents queries the "events" edge of the Workspace entity.
func (_m *Workspace) QueryEvents() *EventQuery {
	return NewWorkspaceClient(_m.config).QueryEvents(_m)
}

// QueryVisitors queries the "visitors" edge of the Workspace entity.
func (_m *Workspace) QueryVisitors() *VisitorQuery {
	return NewWorkspaceClient(_m.config).QueryVisitors(_m)
}

// QueryAPITokens queries the "api_tokens" edge of the Workspace entity.
func (_m *Workspace) QueryAPITokens() *ApiTokenQuery {
	return NewWorkspaceClient(_m.config).QueryAPITokens(_m)
}

// QueryIntegrations queries the "integrations" edge of the Workspace entity.
func (_m *Workspace) QueryIntegrations() *IntegrationQuery {
	return NewWorkspaceClient(_m.config).QueryIntegrations(_m)
}

// QuerySendingDomains queries the "sending_domains" edge of the Workspace entity.
func (_m *Workspace) QuerySendingDomains() *SendingDomainQuery {
	return NewWorkspaceClient(_m.config).QuerySendingDomains(_m)
}

// QueryBroadcasts queries the "broadcasts" edge of the Workspace entity.
func (_m *Workspace) QueryBroadcasts() *BroadcastQuery {
	return NewWorkspaceClient(_m.config).QueryBroadcasts(_m)
}

// QueryBroadcastRecipients queries the "broadcast_recipients" edge of the Workspace entity.
func (_m *Workspace) QueryBroadcastRecipients() *BroadcastRecipientQuery {
	return NewWorkspaceClient(_m.config).QueryBroadcastRecipients(_m)
}

// QueryEmailTemplates queries the "email_templates" edge of the Workspace entity.
func (_m *Workspace) QueryEmailTemplates() *EmailTemplateQuery {
	return NewWorkspaceClient(_m.config).QueryEmailTemplates(_m)
}

// QueryAutomations queries the "automations" edge of the Workspace entity.
func (_m *Workspace) QueryAutomations() *AutomationQuery {
	return NewWorkspaceClient(_m.config).QueryAutomations(_m)
}

// QueryAutomationRuns queries the "automation_runs" edge of the Workspace entity.
func (_m *Workspace) QueryAutomationRuns() *AutomationRunQuery {
	return NewWorkspaceClient(_m.config).QueryAutomationRuns(_m)
}

// QueryWebhookEndpoints queries the "webhook_endpoints" edge of the Workspace entity.
func (_m *Workspace) QueryWebhookEndpoints() *WebhookEndpointQuery {
	return NewWorkspaceClient(_m.config).QueryWebhookEndpoints(_m)
}

// QuerySuppressions queries the "suppressions" edge of the Workspace entity.
func (_m *Workspace) QuerySuppressions() *SuppressionQuery {
	return NewWorkspaceClient(_m.config).QuerySuppressions(_m)
}

// QueryUnsubscribes queries the "unsubscribes" edge of the Workspace entity.
func (_m *Workspace) QueryUnsubscribes() *UnsubscribeQuery {
	return NewWorkspaceClient(_m.config).QueryUnsubscribes(_m)
}

// QueryTransactionalEmails queries the "transactional_emails" edge of the Workspace entity.
func (_m *Workspace) QueryTransactionalEmails() *TransactionalEmailQuery {
	return NewWorkspaceClient(_m.config).QueryTransactionalEmails(_m)
}

// QueryMemberships queries the "memberships" edge of the Workspace entity.
func (_m *Workspace) QueryMemberships() *MembershipQuery {
	return NewWorkspaceClient(_m.config).QueryMemberships(_m)
}

// QueryInvitations queries the "invitations" edge of the Workspace entity.
func (_m *Workspace) QueryInvitations() *InvitationQuery {
	return NewWorkspaceClient(_m.config).QueryInvitations(_m)
}

// Update returns a builder for updating this Workspace.
// Note that you need to call Workspace.Unwrap() before calling this method if this Workspace
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Workspace) Update() *WorkspaceUpdateOne {
	return NewWorkspaceClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Workspace entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Workspace) Unwrap() *Workspace {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Workspace is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Workspace) String() string {
	var builder strings.Builder
	builder.WriteString("Workspace(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("collect_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("ingest_key=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Workspaces is a parsable slice of Workspace.
type Workspaces []*Workspace
