// Code generated by ent, DO NOT EDIT.

package trackingvisitor

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/mokevnin/1mail/backend/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldLTE(FieldID, id))
}

// VisitorID applies equality check predicate on the "visitor_id" field. It's identical to VisitorIDEQ.
func VisitorID(v string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEQ(FieldVisitorID, v))
}

// ProfileID applies equality check predicate on the "profile_id" field. It's identical to ProfileIDEQ.
func ProfileID(v int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEQ(FieldProfileID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEQ(FieldUpdatedAt, v))
}

// LastSeenAt applies equality check predicate on the "last_seen_at" field. It's identical to LastSeenAtEQ.
func LastSeenAt(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEQ(FieldLastSeenAt, v))
}

// VisitorIDEQ applies the EQ predicate on the "visitor_id" field.
func VisitorIDEQ(v string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEQ(FieldVisitorID, v))
}

// VisitorIDNEQ applies the NEQ predicate on the "visitor_id" field.
func VisitorIDNEQ(v string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNEQ(FieldVisitorID, v))
}

// VisitorIDIn applies the In predicate on the "visitor_id" field.
func VisitorIDIn(vs ...string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldIn(FieldVisitorID, vs...))
}

// VisitorIDNotIn applies the NotIn predicate on the "visitor_id" field.
func VisitorIDNotIn(vs ...string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNotIn(FieldVisitorID, vs...))
}

// VisitorIDGT applies the GT predicate on the "visitor_id" field.
func VisitorIDGT(v string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldGT(FieldVisitorID, v))
}

// VisitorIDGTE applies the GTE predicate on the "visitor_id" field.
func VisitorIDGTE(v string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldGTE(FieldVisitorID, v))
}

// VisitorIDLT applies the LT predicate on the "visitor_id" field.
func VisitorIDLT(v string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldLT(FieldVisitorID, v))
}

// VisitorIDLTE applies the LTE predicate on the "visitor_id" field.
func VisitorIDLTE(v string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldLTE(FieldVisitorID, v))
}

// VisitorIDContains applies the Contains predicate on the "visitor_id" field.
func VisitorIDContains(v string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldContains(FieldVisitorID, v))
}

// VisitorIDHasPrefix applies the HasPrefix predicate on the "visitor_id" field.
func VisitorIDHasPrefix(v string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldHasPrefix(FieldVisitorID, v))
}

// VisitorIDHasSuffix applies the HasSuffix predicate on the "visitor_id" field.
func VisitorIDHasSuffix(v string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldHasSuffix(FieldVisitorID, v))
}

// VisitorIDEqualFold applies the EqualFold predicate on the "visitor_id" field.
func VisitorIDEqualFold(v string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEqualFold(FieldVisitorID, v))
}

// VisitorIDContainsFold applies the ContainsFold predicate on the "visitor_id" field.
func VisitorIDContainsFold(v string) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldContainsFold(FieldVisitorID, v))
}

// ProfileIDEQ applies the EQ predicate on the "profile_id" field.
func ProfileIDEQ(v int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEQ(FieldProfileID, v))
}

// ProfileIDNEQ applies the NEQ predicate on the "profile_id" field.
func ProfileIDNEQ(v int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNEQ(FieldProfileID, v))
}

// ProfileIDIn applies the In predicate on the "profile_id" field.
func ProfileIDIn(vs ...int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldIn(FieldProfileID, vs...))
}

// ProfileIDNotIn applies the NotIn predicate on the "profile_id" field.
func ProfileIDNotIn(vs ...int64) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNotIn(FieldProfileID, vs...))
}

// ProfileIDIsNil applies the IsNil predicate on the "profile_id" field.
func ProfileIDIsNil() predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldIsNull(FieldProfileID))
}

// ProfileIDNotNil applies the NotNil predicate on the "profile_id" field.
func ProfileIDNotNil() predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNotNull(FieldProfileID))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldLTE(FieldUpdatedAt, v))
}

// LastSeenAtEQ applies the EQ predicate on the "last_seen_at" field.
func LastSeenAtEQ(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldEQ(FieldLastSeenAt, v))
}

// LastSeenAtNEQ applies the NEQ predicate on the "last_seen_at" field.
func LastSeenAtNEQ(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNEQ(FieldLastSeenAt, v))
}

// LastSeenAtIn applies the In predicate on the "last_seen_at" field.
func LastSeenAtIn(vs ...time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldIn(FieldLastSeenAt, vs...))
}

// LastSeenAtNotIn applies the NotIn predicate on the "last_seen_at" field.
func LastSeenAtNotIn(vs ...time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldNotIn(FieldLastSeenAt, vs...))
}

// LastSeenAtGT applies the GT predicate on the "last_seen_at" field.
func LastSeenAtGT(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldGT(FieldLastSeenAt, v))
}

// LastSeenAtGTE applies the GTE predicate on the "last_seen_at" field.
func LastSeenAtGTE(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldGTE(FieldLastSeenAt, v))
}

// LastSeenAtLT applies the LT predicate on the "last_seen_at" field.
func LastSeenAtLT(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldLT(FieldLastSeenAt, v))
}

// LastSeenAtLTE applies the LTE predicate on the "last_seen_at" field.
func LastSeenAtLTE(v time.Time) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.FieldLTE(FieldLastSeenAt, v))
}

// HasProfile applies the HasEdge predicate on the "profile" edge.
func HasProfile() predicate.TrackingVisitor {
	return predicate.TrackingVisitor(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProfileTable, ProfileColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProfileWith applies the HasEdge predicate on the "profile" edge with a given conditions (other predicates).
func HasProfileWith(preds ...predicate.TrackingProfile) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(func(s *sql.Selector) {
		step := newProfileStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TrackingVisitor) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TrackingVisitor) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TrackingVisitor) predicate.TrackingVisitor {
	return predicate.TrackingVisitor(sql.NotPredicates(p))
}
