apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sphericon.fullname" . }}
  labels:
    {{- include "sphericon.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "sphericon.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sphericon.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: sphericon
          image: {{ include "sphericon.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            {{- include "sphericon.envFrom" . | nindent 12 }}
          env:
            {{- include "sphericon.env" . | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
            {{- if .Values.metrics.enabled }}
            - name: metrics
              containerPort: {{ .Values.metrics.port }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /readyz
              port: http
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
