package site

import (
	"context"
	"io"
	"net/http"
	"strconv"
	"time"

	"github.com/mokevnin/sphericon/ent"
	"github.com/mokevnin/sphericon/ent/membership"
	siteapi "github.com/mokevnin/sphericon/gen/site"
	"github.com/mokevnin/sphericon/internal/accounts"
	"github.com/mokevnin/sphericon/internal/analytics"
	"github.com/mokevnin/sphericon/internal/api/auth"
	"github.com/mokevnin/sphericon/internal/api/site/resources"
	"github.com/mokevnin/sphericon/internal/authtoken"
	"github.com/mokevnin/sphericon/internal/automations"
	"github.com/mokevnin/sphericon/internal/broadcasts"
	"github.com/mokevnin/sphericon/internal/contacts"
	"github.com/mokevnin/sphericon/internal/erasure"
	"github.com/mokevnin/sphericon/internal/eventlog"
	"github.com/mokevnin/sphericon/internal/events"
	"github.com/mokevnin/sphericon/internal/i18n"
	"github.com/mokevnin/sphericon/internal/integrations"
	"github.com/mokevnin/sphericon/internal/oauthserver"
	"github.com/mokevnin/sphericon/internal/outbound"
	"github.com/mokevnin/sphericon/internal/secondfactor"
	"github.com/mokevnin/sphericon/internal/segments"
	"github.com/mokevnin/sphericon/internal/sendingdomains"
	"github.com/mokevnin/sphericon/internal/tags"
	"github.com/mokevnin/sphericon/internal/templates"
	"github.com/mokevnin/sphericon/internal/tracking"
	"github.com/mokevnin/sphericon/internal/webhooks"
)

// mapper turns ent entities into site API resources (generated by goverter).
var mapper = &resources.ConverterImpl{}

// BroadcastEnqueuer is the job-queue seam the broadcasts module sends through
// (river in prod, inline in tests).
type BroadcastEnqueuer = broadcasts.Enqueuer

// WelcomeEnqueuer schedules the platform welcome email after registration. Same
// jobs enqueue seam (river prod, inline tests).
type WelcomeEnqueuer interface {
	EnqueueWelcome(ctx context.Context, email, name string) error
}

// SystemMailEnqueuer schedules the self-service account emails (password reset,
// email verification, email-change confirmation) through the platform system
// sender. Same jobs enqueue seam (river prod, inline tests). The token is minted
// by the handler; the job builds the link.
type SystemMailEnqueuer interface {
	// EnqueuePasswordReset queues the reset mail. With send false the job is queued
	// all the same but nothing is delivered, so forgot-password costs the same
	// for every address.
	EnqueuePasswordReset(ctx context.Context, email, token string, send bool) error
	EnqueueEmailVerification(ctx context.Context, email, token string) error
	EnqueueEmailChangeConfirm(ctx context.Context, email, token string) error
	// EnqueueMemberInvite sends the workspace invite email. It is best-effort:
	// the invite also returns a copy-link, so a missing/failed mailer (common on
	// self-hosted with no SMTP) must not fail the invite.
	EnqueueMemberInvite(ctx context.Context, email, inviteURL, workspaceName, inviterName string) error
	// EnqueueSecondFactorRequired emails the Workspace's Users without a Second
	// factor that its Two-factor requirement is now on, with their deadline (ADR 0020).
	EnqueueSecondFactorRequired(ctx context.Context, workspaceID int64) error
}

type Handlers struct {
	accounts       *accounts.Accounts
	attempts       *accounts.Attempts
	bus            *events.Bus
	webhooks       *webhooks.Module
	broadcasts     *broadcasts.Module
	welcome        WelcomeEnqueuer
	sysmail        SystemMailEnqueuer
	sendingDomains *sendingdomains.Module
	integrations   *integrations.Module
	tokens         *authtoken.Signer
	tracker        *tracking.Tracker
	appURL         string
	outbound       *outbound.Module
	segments       *segments.Module
	eventlog       *eventlog.Module
	contacts       *contacts.Module
	erasure        *erasure.Module
	tags           *tags.Module
	templates      *templates.Module
	automations    *automations.Module
	oauth          *oauthserver.Service
	audit          AuditLog
	analytics      *analytics.Module
	sessions       *auth.Sessions
	secondFactor   *secondfactor.Module
	now            func() time.Time
	// challenges signs the login challenge on the env clock (ADR 0020).
	challenges *authtoken.Signer
}

// AuditLog is the read seam of the Enterprise Audit log (ADR 0022), implemented by
// ee/audit. Core knows only this interface: without a license Licensed is false and
// the page answers 402.
type AuditLog interface {
	Licensed() bool
	// Entries returns up to limit entries matching the filter, newest first, preceding
	// the cursor entry id (0 = from the newest), and the next page's cursor (0 = last page).
	Entries(ctx context.Context, s *ent.Scoped, f events.AuditFilter, cursor int64, limit int) ([]*ent.AuditEntry, int64, error)
	// ExportCSV streams the entries matching the filter, newest first, as CSV.
	ExportCSV(ctx context.Context, s *ent.Scoped, f events.AuditFilter, w io.Writer) error
	// RetentionLicensed reports whether the retention window may be set (ADR 0014).
	RetentionLicensed() bool
}

// Deps is everything the /site handlers are built from. The domain modules are
// the shared singletons the composition root registers once, so /site and /api
// cannot diverge on how a module is constructed.
type Deps struct {
	Accounts *accounts.Accounts
	// Attempts counts failed logins and password-reset mails per account (ADR
	// 0025); login and forgot-password share it.
	Attempts       *accounts.Attempts
	OAuth          *oauthserver.Service
	Bus            *events.Bus
	Webhooks       *webhooks.Module
	Outbound       *outbound.Module
	Segments       *segments.Module
	EventLog       *eventlog.Module
	Contacts       *contacts.Module
	Erasure        *erasure.Module
	Tags           *tags.Module
	Templates      *templates.Module
	Automations    *automations.Module
	Broadcasts     *broadcasts.Module
	Welcome        WelcomeEnqueuer
	SysMail        SystemMailEnqueuer
	SendingDomains *sendingdomains.Module
	Integrations   *integrations.Module
	Tokens         *authtoken.Signer
	Tracker        *tracking.Tracker
	AppURL         string
	Audit          AuditLog
	Analytics      *analytics.Module
	// Sessions issues the session cookie on login (ADR 0020). The composition
	// root (server.New) builds it from the instance secret and SESSION_TTL.
	Sessions *auth.Sessions
	// SecondFactor enrolls and verifies a User's TOTP Second factor (ADR 0020).
	SecondFactor *secondfactor.Module
	// Clock is the time the site session's expiry and a Two-factor requirement's
	// grace are checked against (ADR 0020); nil means time.Now. Tests inject one to
	// move past a session's lifetime or a grace period.
	Clock func() time.Time
}

func NewHandlers(d Deps) *Handlers {
	now := d.Clock
	if now == nil {
		now = time.Now
	}
	return &Handlers{
		accounts: d.Accounts, attempts: d.Attempts, bus: d.Bus, webhooks: d.Webhooks, outbound: d.Outbound,
		segments: d.Segments, eventlog: d.EventLog, contacts: d.Contacts, erasure: d.Erasure, tags: d.Tags, templates: d.Templates,
		automations: d.Automations, broadcasts: d.Broadcasts, welcome: d.Welcome,
		sysmail: d.SysMail, sendingDomains: d.SendingDomains, integrations: d.Integrations, tokens: d.Tokens, tracker: d.Tracker, appURL: d.AppURL,
		oauth: d.OAuth, audit: d.Audit, analytics: d.Analytics, sessions: d.Sessions, secondFactor: d.SecondFactor, now: now,
		challenges: d.Tokens.WithClock(d.Clock),
	}
}

var _ siteapi.Handler = (*Handlers)(nil)

// scopedFor is the site's construction point of the scoped client (ADR 0017): it
// resolves the Workspace addressed by the /w/{slug} path segment through the
// authenticated user's Membership (accounts.Scope) and returns its scoped client.
// Handlers pass the result to the domain modules and never build a *ent.Scoped from
// an int64. Returns an ent NotFound error (mapped to 404) when the slug does not
// exist or the user is not a member.
func (h *Handlers) scopedFor(ctx context.Context, slug string) (*ent.Scoped, error) {
	s, _, err := h.scopedWithRoleFor(ctx, slug)
	return s, err
}

// actor is the signed-in User as the actor of an Audit entry (ADR 0022), with the
// display name snapshotted. A name that cannot be loaded is left empty: the entry is
// still worth recording.
func (h *Handlers) actor(ctx context.Context) events.Actor {
	a := auth.GetSiteAuth(ctx)
	if a == nil {
		return events.Actor{}
	}
	actor := events.Actor{Kind: events.ActorUser, ID: strconv.FormatInt(a.UserID, 10)}
	if u, err := h.accounts.User(ctx, a.UserID); err == nil {
		actor.Name = u.Name
	}
	return actor
}

// scopedWithRoleFor is scopedFor plus the caller's role, for owner/admin-gated
// actions.
func (h *Handlers) scopedWithRoleFor(ctx context.Context, slug string) (*ent.Scoped, membership.Role, error) {
	s, m, err := h.membershipFor(ctx, slug)
	if err != nil {
		return nil, "", err
	}
	return s, m.Role, nil
}

// membershipFor is scopedFor plus the caller's Membership (its User and Workspace
// loaded). It is where the Two-factor requirement is enforced (ADR 0020): once a
// User's grace in a requiring Workspace has ended without a Second factor, every
// request to that Workspace fails with errSecondFactorRequired (403
// second_factor_required); other Workspaces and the /me endpoints are unaffected.
func (h *Handlers) membershipFor(ctx context.Context, slug string) (*ent.Scoped, *ent.Membership, error) {
	s, m, err := h.membershipEvenIfWithheld(ctx, slug)
	if err != nil {
		return nil, nil, err
	}
	if secondfactor.Withheld(m, h.now()) {
		return nil, nil, errSecondFactorRequired{}
	}
	return s, m, nil
}

// membershipEvenIfWithheld is membershipFor without the Two-factor requirement
// check. Only turning the requirement off uses it: an Owner or Admin withheld by
// the requirement must still be able to lift it (ADR 0020).
func (h *Handlers) membershipEvenIfWithheld(ctx context.Context, slug string) (*ent.Scoped, *ent.Membership, error) {
	a := auth.GetSiteAuth(ctx)
	if a == nil {
		return nil, nil, &ent.NotFoundError{}
	}
	return h.accounts.Scope(ctx, a.UserID, slug)
}

// errSecondFactorRequired is secondfactor.ErrRequired as the problem the site
// answers it with. Returned as an error, it is rendered by the server's error
// handler, which reads it through its Problem method.
type errSecondFactorRequired struct{}

func (errSecondFactorRequired) Error() string { return secondfactor.ErrRequired.Error() }
func (errSecondFactorRequired) Unwrap() error { return secondfactor.ErrRequired }

// Problem is the 403 second_factor_required answer.
func (errSecondFactorRequired) Problem() (status int, code, detail string) {
	return http.StatusForbidden, string(siteapi.ProblemCodeSecondFactorRequired), i18n.T("errors.second_factor_required", nil)
}
