package site

import (
	"context"
	"fmt"
	"time"

	"github.com/mokevnin/1mail/ent"
	"github.com/mokevnin/1mail/ent/workspace"
	siteapi "github.com/mokevnin/1mail/gen/site"
	"github.com/mokevnin/1mail/internal/api/auth"
	"github.com/mokevnin/1mail/internal/api/site/resources"
	"github.com/mokevnin/1mail/internal/events"
	"github.com/mokevnin/1mail/internal/messaging"
	"github.com/mokevnin/1mail/internal/pubsub"
	"github.com/mokevnin/1mail/internal/secrets"
	"github.com/mokevnin/1mail/internal/service"
)

// mapper turns ent entities into site API resources (generated by goverter).
var mapper = &resources.ConverterImpl{}

// BroadcastEnqueuer schedules a broadcast for asynchronous dispatch. It is a
// narrow seam over the river-backed jobs client so handlers stay testable (tests
// pass a no-op). A nil scheduledAt means send as soon as possible.
type BroadcastEnqueuer interface {
	EnqueueBroadcast(ctx context.Context, broadcastID int64, scheduledAt *time.Time) error
}

// AutomationTrigger enrolls a contact into automations matching an Event action.
// Same testable-seam pattern as BroadcastEnqueuer (tests pass a no-op).
type AutomationTrigger interface {
	OnEvent(ctx context.Context, workspaceID, contactID int64, action string) error
}

type Handlers struct {
	ent      *ent.Client
	pubsub   *pubsub.PubSub
	bus      *events.Bus
	cipher   *secrets.Cipher
	catalog  *messaging.Catalog
	enqueuer BroadcastEnqueuer
	trigger  AutomationTrigger
}

func NewHandlers(client *ent.Client, ps *pubsub.PubSub, bus *events.Bus, cipher *secrets.Cipher, catalog *messaging.Catalog, enqueuer BroadcastEnqueuer, trigger AutomationTrigger) *Handlers {
	return &Handlers{ent: client, pubsub: ps, bus: bus, cipher: cipher, catalog: catalog, enqueuer: enqueuer, trigger: trigger}
}

var _ siteapi.Handler = (*Handlers)(nil)

// workspaceID resolves the workspace addressed by the /w/{slug} path segment,
// scoped to the authenticated user. Returns an ent NotFound error (so callers
// can map it to 404) when the slug does not exist or is not owned by the user.
func (h *Handlers) workspaceID(ctx context.Context, slug string) (int64, error) {
	a := auth.GetSiteAuth(ctx)
	if a == nil {
		return 0, &ent.NotFoundError{}
	}
	ws, err := h.ent.Workspace.Query().
		Where(workspace.Slug(slug), workspace.UserID(a.UserID)).
		Only(ctx)
	if err != nil {
		return 0, err
	}
	return ws.ID, nil
}

// createDefaultWorkspace creates the user's initial workspace with a unique slug
// derived from name (falling back to "workspace"). Workspace slugs are globally
// unique, so on collision a numeric suffix is appended.
func (h *Handlers) createDefaultWorkspace(ctx context.Context, userID int64, name string) (*ent.Workspace, error) {
	base := service.Slugify(name)
	if base == "" {
		base = "workspace"
	}
	for i := 0; ; i++ {
		slug := base
		if i > 0 {
			slug = fmt.Sprintf("%s-%d", base, i+1)
		}
		exists, err := h.ent.Workspace.Query().Where(workspace.Slug(slug)).Exist(ctx)
		if err != nil {
			return nil, err
		}
		if exists {
			continue
		}
		collectKey, err := service.GenerateCollectKey()
		if err != nil {
			return nil, err
		}
		ws, err := h.ent.Workspace.Create().
			SetName(name).
			SetSlug(slug).
			SetCollectKey(collectKey).
			SetUserID(userID).
			Save(ctx)
		if service.IsUniqueViolation(err) {
			continue // lost a race on the slug; try the next suffix
		}
		if err != nil {
			return nil, err
		}
		return ws, nil
	}
}
