package site

import (
	"context"
	"io"
	"strconv"

	"github.com/mokevnin/1mail/ent"
	"github.com/mokevnin/1mail/ent/membership"
	siteapi "github.com/mokevnin/1mail/gen/site"
	"github.com/mokevnin/1mail/internal/accounts"
	"github.com/mokevnin/1mail/internal/api/auth"
	"github.com/mokevnin/1mail/internal/api/site/resources"
	"github.com/mokevnin/1mail/internal/authtoken"
	"github.com/mokevnin/1mail/internal/automations"
	"github.com/mokevnin/1mail/internal/broadcasts"
	"github.com/mokevnin/1mail/internal/contacts"
	"github.com/mokevnin/1mail/internal/eventlog"
	"github.com/mokevnin/1mail/internal/events"
	"github.com/mokevnin/1mail/internal/messaging"
	"github.com/mokevnin/1mail/internal/oauthserver"
	"github.com/mokevnin/1mail/internal/outbound"
	"github.com/mokevnin/1mail/internal/secrets"
	"github.com/mokevnin/1mail/internal/segments"
	"github.com/mokevnin/1mail/internal/tags"
	"github.com/mokevnin/1mail/internal/tracking"
)

// mapper turns ent entities into site API resources (generated by goverter).
var mapper = &resources.ConverterImpl{}

// BroadcastEnqueuer is the job-queue seam the broadcasts module sends through
// (river in prod, inline in tests).
type BroadcastEnqueuer = broadcasts.Enqueuer

// WelcomeEnqueuer schedules the platform welcome email after registration. Same
// jobs enqueue seam (river prod, inline tests).
type WelcomeEnqueuer interface {
	EnqueueWelcome(ctx context.Context, email, name string) error
}

// SystemMailEnqueuer schedules the self-service account emails (password reset,
// email verification, email-change confirmation) through the platform system
// sender. Same jobs enqueue seam (river prod, inline tests). The token is minted
// by the handler; the job builds the link.
type SystemMailEnqueuer interface {
	EnqueuePasswordReset(ctx context.Context, email, token string) error
	EnqueueEmailVerification(ctx context.Context, email, token string) error
	EnqueueEmailChangeConfirm(ctx context.Context, email, token string) error
	// EnqueueMemberInvite sends the workspace invite email. It is best-effort:
	// the invite also returns a copy-link, so a missing/failed mailer (common on
	// self-hosted with no SMTP) must not fail the invite.
	EnqueueMemberInvite(ctx context.Context, email, inviteURL, workspaceName, inviterName string) error
}

// SendingDomainVerifyEnqueuer schedules an immediate DKIM re-check of one
// Sending domain (the "Verify" button). Same jobs enqueue seam (river prod,
// inline tests).
type SendingDomainVerifyEnqueuer interface {
	EnqueueSendingDomainVerify(ctx context.Context, sendingDomainID int64) error
}

type Handlers struct {
	accounts     *accounts.Accounts
	bus          *events.Bus
	cipher       *secrets.Cipher
	catalog      *messaging.Catalog
	broadcasts   *broadcasts.Module
	welcome      WelcomeEnqueuer
	sysmail      SystemMailEnqueuer
	domainVerify SendingDomainVerifyEnqueuer
	tokens       *authtoken.Signer
	tracker      *tracking.Tracker
	appURL       string
	outbound     *outbound.Module
	segments     *segments.Module
	eventlog     *eventlog.Module
	contacts     *contacts.Module
	tags         *tags.Module
	automations  *automations.Module
	oauth        *oauthserver.Service
	audit        AuditLog
}

// AuditLog is the read seam of the Enterprise Audit log (ADR 0022), implemented by
// ee/audit. Core knows only this interface: without a license Licensed is false and
// the page answers 402.
type AuditLog interface {
	Licensed() bool
	// Entries returns up to limit entries matching the filter, newest first, preceding
	// the cursor entry id (0 = from the newest), and the next page's cursor (0 = last page).
	Entries(ctx context.Context, s *ent.Scoped, f events.AuditFilter, cursor int64, limit int) ([]*ent.AuditEntry, int64, error)
	// ExportCSV streams the entries matching the filter, newest first, as CSV.
	ExportCSV(ctx context.Context, s *ent.Scoped, f events.AuditFilter, w io.Writer) error
	// RetentionLicensed reports whether the retention window may be set (ADR 0014).
	RetentionLicensed() bool
}

// Deps is everything the /site handlers are built from. The domain modules are
// the shared singletons the composition root registers once, so /site and /api
// cannot diverge on how a module is constructed.
type Deps struct {
	Accounts     *accounts.Accounts
	OAuth        *oauthserver.Service
	Bus          *events.Bus
	Cipher       *secrets.Cipher
	Catalog      *messaging.Catalog
	Outbound     *outbound.Module
	Segments     *segments.Module
	EventLog     *eventlog.Module
	Contacts     *contacts.Module
	Tags         *tags.Module
	Automations  *automations.Module
	Broadcasts   *broadcasts.Module
	Welcome      WelcomeEnqueuer
	SysMail      SystemMailEnqueuer
	DomainVerify SendingDomainVerifyEnqueuer
	Tokens       *authtoken.Signer
	Tracker      *tracking.Tracker
	AppURL       string
	Audit        AuditLog
}

func NewHandlers(d Deps) *Handlers {
	return &Handlers{
		accounts: d.Accounts, bus: d.Bus, cipher: d.Cipher, catalog: d.Catalog, outbound: d.Outbound,
		segments: d.Segments, eventlog: d.EventLog, contacts: d.Contacts, tags: d.Tags,
		automations: d.Automations, broadcasts: d.Broadcasts, welcome: d.Welcome,
		sysmail: d.SysMail, domainVerify: d.DomainVerify, tokens: d.Tokens, tracker: d.Tracker, appURL: d.AppURL,
		oauth: d.OAuth, audit: d.Audit,
	}
}

var _ siteapi.Handler = (*Handlers)(nil)

// scopedFor is the site's construction point of the scoped client (ADR 0017): it
// resolves the Workspace addressed by the /w/{slug} path segment through the
// authenticated user's Membership (accounts.Scope) and returns its scoped client.
// Handlers pass the result to the domain modules and never build a *ent.Scoped from
// an int64. Returns an ent NotFound error (mapped to 404) when the slug does not
// exist or the user is not a member.
func (h *Handlers) scopedFor(ctx context.Context, slug string) (*ent.Scoped, error) {
	s, _, err := h.scopedWithRoleFor(ctx, slug)
	return s, err
}

// actor is the signed-in User as the actor of an Audit entry (ADR 0022), with the
// display name snapshotted. A name that cannot be loaded is left empty: the entry is
// still worth recording.
func (h *Handlers) actor(ctx context.Context) events.Actor {
	a := auth.GetSiteAuth(ctx)
	if a == nil {
		return events.Actor{}
	}
	actor := events.Actor{Kind: events.ActorUser, ID: strconv.FormatInt(a.UserID, 10)}
	if u, err := h.accounts.User(ctx, a.UserID); err == nil {
		actor.Name = u.Name
	}
	return actor
}

// scopedWithRoleFor is scopedFor plus the caller's role, for owner/admin-gated
// actions.
func (h *Handlers) scopedWithRoleFor(ctx context.Context, slug string) (*ent.Scoped, membership.Role, error) {
	a := auth.GetSiteAuth(ctx)
	if a == nil {
		return nil, "", &ent.NotFoundError{}
	}
	return h.accounts.Scope(ctx, a.UserID, slug)
}
