// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package main

import (
	"context"
	"sync"
)

// Ensure, that workspaceOpsMock does implement workspaceOps.
// If this is not the case, regenerate this file with moq.
var _ workspaceOps = &workspaceOpsMock{}

// workspaceOpsMock is a mock implementation of workspaceOps.
//
//	func TestSomethingThatUsesworkspaceOps(t *testing.T) {
//
//		// make and configure a mocked workspaceOps
//		mockedworkspaceOps := &workspaceOpsMock{
//			SuspendWorkspaceFunc: func(ctx context.Context, slug string, by string, reason string) (bool, error) {
//				panic("mock out the SuspendWorkspace method")
//			},
//			UnsuspendWorkspaceFunc: func(ctx context.Context, slug string) (bool, error) {
//				panic("mock out the UnsuspendWorkspace method")
//			},
//		}
//
//		// use mockedworkspaceOps in code that requires workspaceOps
//		// and then make assertions.
//
//	}
type workspaceOpsMock struct {
	// SuspendWorkspaceFunc mocks the SuspendWorkspace method.
	SuspendWorkspaceFunc func(ctx context.Context, slug string, by string, reason string) (bool, error)

	// UnsuspendWorkspaceFunc mocks the UnsuspendWorkspace method.
	UnsuspendWorkspaceFunc func(ctx context.Context, slug string) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// SuspendWorkspace holds details about calls to the SuspendWorkspace method.
		SuspendWorkspace []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Slug is the slug argument value.
			Slug string
			// By is the by argument value.
			By string
			// Reason is the reason argument value.
			Reason string
		}
		// UnsuspendWorkspace holds details about calls to the UnsuspendWorkspace method.
		UnsuspendWorkspace []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Slug is the slug argument value.
			Slug string
		}
	}
	lockSuspendWorkspace   sync.RWMutex
	lockUnsuspendWorkspace sync.RWMutex
}

// SuspendWorkspace calls SuspendWorkspaceFunc.
func (mock *workspaceOpsMock) SuspendWorkspace(ctx context.Context, slug string, by string, reason string) (bool, error) {
	if mock.SuspendWorkspaceFunc == nil {
		panic("workspaceOpsMock.SuspendWorkspaceFunc: method is nil but workspaceOps.SuspendWorkspace was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Slug   string
		By     string
		Reason string
	}{
		Ctx:    ctx,
		Slug:   slug,
		By:     by,
		Reason: reason,
	}
	mock.lockSuspendWorkspace.Lock()
	mock.calls.SuspendWorkspace = append(mock.calls.SuspendWorkspace, callInfo)
	mock.lockSuspendWorkspace.Unlock()
	return mock.SuspendWorkspaceFunc(ctx, slug, by, reason)
}

// SuspendWorkspaceCalls gets all the calls that were made to SuspendWorkspace.
// Check the length with:
//
//	len(mockedworkspaceOps.SuspendWorkspaceCalls())
func (mock *workspaceOpsMock) SuspendWorkspaceCalls() []struct {
	Ctx    context.Context
	Slug   string
	By     string
	Reason string
} {
	var calls []struct {
		Ctx    context.Context
		Slug   string
		By     string
		Reason string
	}
	mock.lockSuspendWorkspace.RLock()
	calls = mock.calls.SuspendWorkspace
	mock.lockSuspendWorkspace.RUnlock()
	return calls
}

// UnsuspendWorkspace calls UnsuspendWorkspaceFunc.
func (mock *workspaceOpsMock) UnsuspendWorkspace(ctx context.Context, slug string) (bool, error) {
	if mock.UnsuspendWorkspaceFunc == nil {
		panic("workspaceOpsMock.UnsuspendWorkspaceFunc: method is nil but workspaceOps.UnsuspendWorkspace was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Slug string
	}{
		Ctx:  ctx,
		Slug: slug,
	}
	mock.lockUnsuspendWorkspace.Lock()
	mock.calls.UnsuspendWorkspace = append(mock.calls.UnsuspendWorkspace, callInfo)
	mock.lockUnsuspendWorkspace.Unlock()
	return mock.UnsuspendWorkspaceFunc(ctx, slug)
}

// UnsuspendWorkspaceCalls gets all the calls that were made to UnsuspendWorkspace.
// Check the length with:
//
//	len(mockedworkspaceOps.UnsuspendWorkspaceCalls())
func (mock *workspaceOpsMock) UnsuspendWorkspaceCalls() []struct {
	Ctx  context.Context
	Slug string
} {
	var calls []struct {
		Ctx  context.Context
		Slug string
	}
	mock.lockUnsuspendWorkspace.RLock()
	calls = mock.calls.UnsuspendWorkspace
	mock.lockUnsuspendWorkspace.RUnlock()
	return calls
}

// Ensure, that operatorOpsMock does implement operatorOps.
// If this is not the case, regenerate this file with moq.
var _ operatorOps = &operatorOpsMock{}

// operatorOpsMock is a mock implementation of operatorOps.
//
//	func TestSomethingThatUsesoperatorOps(t *testing.T) {
//
//		// make and configure a mocked operatorOps
//		mockedoperatorOps := &operatorOpsMock{
//			CreateOperatorFunc: func(ctx context.Context, email string) (string, error) {
//				panic("mock out the CreateOperator method")
//			},
//			ResetOperatorTOTPFunc: func(ctx context.Context, email string) error {
//				panic("mock out the ResetOperatorTOTP method")
//			},
//		}
//
//		// use mockedoperatorOps in code that requires operatorOps
//		// and then make assertions.
//
//	}
type operatorOpsMock struct {
	// CreateOperatorFunc mocks the CreateOperator method.
	CreateOperatorFunc func(ctx context.Context, email string) (string, error)

	// ResetOperatorTOTPFunc mocks the ResetOperatorTOTP method.
	ResetOperatorTOTPFunc func(ctx context.Context, email string) error

	// calls tracks calls to the methods.
	calls struct {
		// CreateOperator holds details about calls to the CreateOperator method.
		CreateOperator []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// ResetOperatorTOTP holds details about calls to the ResetOperatorTOTP method.
		ResetOperatorTOTP []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
	}
	lockCreateOperator    sync.RWMutex
	lockResetOperatorTOTP sync.RWMutex
}

// CreateOperator calls CreateOperatorFunc.
func (mock *operatorOpsMock) CreateOperator(ctx context.Context, email string) (string, error) {
	if mock.CreateOperatorFunc == nil {
		panic("operatorOpsMock.CreateOperatorFunc: method is nil but operatorOps.CreateOperator was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockCreateOperator.Lock()
	mock.calls.CreateOperator = append(mock.calls.CreateOperator, callInfo)
	mock.lockCreateOperator.Unlock()
	return mock.CreateOperatorFunc(ctx, email)
}

// CreateOperatorCalls gets all the calls that were made to CreateOperator.
// Check the length with:
//
//	len(mockedoperatorOps.CreateOperatorCalls())
func (mock *operatorOpsMock) CreateOperatorCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockCreateOperator.RLock()
	calls = mock.calls.CreateOperator
	mock.lockCreateOperator.RUnlock()
	return calls
}

// ResetOperatorTOTP calls ResetOperatorTOTPFunc.
func (mock *operatorOpsMock) ResetOperatorTOTP(ctx context.Context, email string) error {
	if mock.ResetOperatorTOTPFunc == nil {
		panic("operatorOpsMock.ResetOperatorTOTPFunc: method is nil but operatorOps.ResetOperatorTOTP was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockResetOperatorTOTP.Lock()
	mock.calls.ResetOperatorTOTP = append(mock.calls.ResetOperatorTOTP, callInfo)
	mock.lockResetOperatorTOTP.Unlock()
	return mock.ResetOperatorTOTPFunc(ctx, email)
}

// ResetOperatorTOTPCalls gets all the calls that were made to ResetOperatorTOTP.
// Check the length with:
//
//	len(mockedoperatorOps.ResetOperatorTOTPCalls())
func (mock *operatorOpsMock) ResetOperatorTOTPCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockResetOperatorTOTP.RLock()
	calls = mock.calls.ResetOperatorTOTP
	mock.lockResetOperatorTOTP.RUnlock()
	return calls
}
