// Code generated by ent, DO NOT EDIT.

package workspace

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the workspace type in the database.
	Label = "workspace"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldCollectKey holds the string denoting the collect_key field in the database.
	FieldCollectKey = "collect_key"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeContacts holds the string denoting the contacts edge name in mutations.
	EdgeContacts = "contacts"
	// EdgeSegments holds the string denoting the segments edge name in mutations.
	EdgeSegments = "segments"
	// EdgeEvents holds the string denoting the events edge name in mutations.
	EdgeEvents = "events"
	// EdgeTrackingProfiles holds the string denoting the tracking_profiles edge name in mutations.
	EdgeTrackingProfiles = "tracking_profiles"
	// EdgeTrackingVisitors holds the string denoting the tracking_visitors edge name in mutations.
	EdgeTrackingVisitors = "tracking_visitors"
	// EdgeAPITokens holds the string denoting the api_tokens edge name in mutations.
	EdgeAPITokens = "api_tokens"
	// EdgeIntegrations holds the string denoting the integrations edge name in mutations.
	EdgeIntegrations = "integrations"
	// EdgeBroadcasts holds the string denoting the broadcasts edge name in mutations.
	EdgeBroadcasts = "broadcasts"
	// EdgeBroadcastRecipients holds the string denoting the broadcast_recipients edge name in mutations.
	EdgeBroadcastRecipients = "broadcast_recipients"
	// EdgeEmailTemplates holds the string denoting the email_templates edge name in mutations.
	EdgeEmailTemplates = "email_templates"
	// EdgeAutomations holds the string denoting the automations edge name in mutations.
	EdgeAutomations = "automations"
	// EdgeAutomationRuns holds the string denoting the automation_runs edge name in mutations.
	EdgeAutomationRuns = "automation_runs"
	// EdgeWebhookEndpoints holds the string denoting the webhook_endpoints edge name in mutations.
	EdgeWebhookEndpoints = "webhook_endpoints"
	// EdgeSuppressions holds the string denoting the suppressions edge name in mutations.
	EdgeSuppressions = "suppressions"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the workspace in the database.
	Table = "workspaces"
	// ContactsTable is the table that holds the contacts relation/edge.
	ContactsTable = "contacts"
	// ContactsInverseTable is the table name for the Contact entity.
	// It exists in this package in order to avoid circular dependency with the "contact" package.
	ContactsInverseTable = "contacts"
	// ContactsColumn is the table column denoting the contacts relation/edge.
	ContactsColumn = "workspace_id"
	// SegmentsTable is the table that holds the segments relation/edge.
	SegmentsTable = "segments"
	// SegmentsInverseTable is the table name for the Segment entity.
	// It exists in this package in order to avoid circular dependency with the "segment" package.
	SegmentsInverseTable = "segments"
	// SegmentsColumn is the table column denoting the segments relation/edge.
	SegmentsColumn = "workspace_id"
	// EventsTable is the table that holds the events relation/edge.
	EventsTable = "events"
	// EventsInverseTable is the table name for the Event entity.
	// It exists in this package in order to avoid circular dependency with the "event" package.
	EventsInverseTable = "events"
	// EventsColumn is the table column denoting the events relation/edge.
	EventsColumn = "workspace_id"
	// TrackingProfilesTable is the table that holds the tracking_profiles relation/edge.
	TrackingProfilesTable = "tracking_profiles"
	// TrackingProfilesInverseTable is the table name for the TrackingProfile entity.
	// It exists in this package in order to avoid circular dependency with the "trackingprofile" package.
	TrackingProfilesInverseTable = "tracking_profiles"
	// TrackingProfilesColumn is the table column denoting the tracking_profiles relation/edge.
	TrackingProfilesColumn = "workspace_id"
	// TrackingVisitorsTable is the table that holds the tracking_visitors relation/edge.
	TrackingVisitorsTable = "tracking_visitors"
	// TrackingVisitorsInverseTable is the table name for the TrackingVisitor entity.
	// It exists in this package in order to avoid circular dependency with the "trackingvisitor" package.
	TrackingVisitorsInverseTable = "tracking_visitors"
	// TrackingVisitorsColumn is the table column denoting the tracking_visitors relation/edge.
	TrackingVisitorsColumn = "workspace_id"
	// APITokensTable is the table that holds the api_tokens relation/edge.
	APITokensTable = "api_tokens"
	// APITokensInverseTable is the table name for the ApiToken entity.
	// It exists in this package in order to avoid circular dependency with the "apitoken" package.
	APITokensInverseTable = "api_tokens"
	// APITokensColumn is the table column denoting the api_tokens relation/edge.
	APITokensColumn = "workspace_id"
	// IntegrationsTable is the table that holds the integrations relation/edge.
	IntegrationsTable = "integrations"
	// IntegrationsInverseTable is the table name for the Integration entity.
	// It exists in this package in order to avoid circular dependency with the "integration" package.
	IntegrationsInverseTable = "integrations"
	// IntegrationsColumn is the table column denoting the integrations relation/edge.
	IntegrationsColumn = "workspace_id"
	// BroadcastsTable is the table that holds the broadcasts relation/edge.
	BroadcastsTable = "broadcasts"
	// BroadcastsInverseTable is the table name for the Broadcast entity.
	// It exists in this package in order to avoid circular dependency with the "broadcast" package.
	BroadcastsInverseTable = "broadcasts"
	// BroadcastsColumn is the table column denoting the broadcasts relation/edge.
	BroadcastsColumn = "workspace_id"
	// BroadcastRecipientsTable is the table that holds the broadcast_recipients relation/edge.
	BroadcastRecipientsTable = "broadcast_recipients"
	// BroadcastRecipientsInverseTable is the table name for the BroadcastRecipient entity.
	// It exists in this package in order to avoid circular dependency with the "broadcastrecipient" package.
	BroadcastRecipientsInverseTable = "broadcast_recipients"
	// BroadcastRecipientsColumn is the table column denoting the broadcast_recipients relation/edge.
	BroadcastRecipientsColumn = "workspace_id"
	// EmailTemplatesTable is the table that holds the email_templates relation/edge.
	EmailTemplatesTable = "email_templates"
	// EmailTemplatesInverseTable is the table name for the EmailTemplate entity.
	// It exists in this package in order to avoid circular dependency with the "emailtemplate" package.
	EmailTemplatesInverseTable = "email_templates"
	// EmailTemplatesColumn is the table column denoting the email_templates relation/edge.
	EmailTemplatesColumn = "workspace_id"
	// AutomationsTable is the table that holds the automations relation/edge.
	AutomationsTable = "automations"
	// AutomationsInverseTable is the table name for the Automation entity.
	// It exists in this package in order to avoid circular dependency with the "automation" package.
	AutomationsInverseTable = "automations"
	// AutomationsColumn is the table column denoting the automations relation/edge.
	AutomationsColumn = "workspace_id"
	// AutomationRunsTable is the table that holds the automation_runs relation/edge.
	AutomationRunsTable = "automation_runs"
	// AutomationRunsInverseTable is the table name for the AutomationRun entity.
	// It exists in this package in order to avoid circular dependency with the "automationrun" package.
	AutomationRunsInverseTable = "automation_runs"
	// AutomationRunsColumn is the table column denoting the automation_runs relation/edge.
	AutomationRunsColumn = "workspace_id"
	// WebhookEndpointsTable is the table that holds the webhook_endpoints relation/edge.
	WebhookEndpointsTable = "webhook_endpoints"
	// WebhookEndpointsInverseTable is the table name for the WebhookEndpoint entity.
	// It exists in this package in order to avoid circular dependency with the "webhookendpoint" package.
	WebhookEndpointsInverseTable = "webhook_endpoints"
	// WebhookEndpointsColumn is the table column denoting the webhook_endpoints relation/edge.
	WebhookEndpointsColumn = "workspace_id"
	// SuppressionsTable is the table that holds the suppressions relation/edge.
	SuppressionsTable = "suppressions"
	// SuppressionsInverseTable is the table name for the Suppression entity.
	// It exists in this package in order to avoid circular dependency with the "suppression" package.
	SuppressionsInverseTable = "suppressions"
	// SuppressionsColumn is the table column denoting the suppressions relation/edge.
	SuppressionsColumn = "workspace_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "workspaces"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for workspace fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSlug,
	FieldCollectKey,
	FieldUserID,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// CollectKeyValidator is a validator for the "collect_key" field. It is called by the builders before save.
	CollectKeyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the Workspace queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByCollectKey orders the results by the collect_key field.
func ByCollectKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCollectKey, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByContactsCount orders the results by contacts count.
func ByContactsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newContactsStep(), opts...)
	}
}

// ByContacts orders the results by contacts terms.
func ByContacts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newContactsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySegmentsCount orders the results by segments count.
func BySegmentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSegmentsStep(), opts...)
	}
}

// BySegments orders the results by segments terms.
func BySegments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSegmentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEventsCount orders the results by events count.
func ByEventsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEventsStep(), opts...)
	}
}

// ByEvents orders the results by events terms.
func ByEvents(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEventsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTrackingProfilesCount orders the results by tracking_profiles count.
func ByTrackingProfilesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTrackingProfilesStep(), opts...)
	}
}

// ByTrackingProfiles orders the results by tracking_profiles terms.
func ByTrackingProfiles(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTrackingProfilesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByTrackingVisitorsCount orders the results by tracking_visitors count.
func ByTrackingVisitorsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newTrackingVisitorsStep(), opts...)
	}
}

// ByTrackingVisitors orders the results by tracking_visitors terms.
func ByTrackingVisitors(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTrackingVisitorsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAPITokensCount orders the results by api_tokens count.
func ByAPITokensCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAPITokensStep(), opts...)
	}
}

// ByAPITokens orders the results by api_tokens terms.
func ByAPITokens(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAPITokensStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByIntegrationsCount orders the results by integrations count.
func ByIntegrationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newIntegrationsStep(), opts...)
	}
}

// ByIntegrations orders the results by integrations terms.
func ByIntegrations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newIntegrationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBroadcastsCount orders the results by broadcasts count.
func ByBroadcastsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBroadcastsStep(), opts...)
	}
}

// ByBroadcasts orders the results by broadcasts terms.
func ByBroadcasts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBroadcastsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBroadcastRecipientsCount orders the results by broadcast_recipients count.
func ByBroadcastRecipientsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBroadcastRecipientsStep(), opts...)
	}
}

// ByBroadcastRecipients orders the results by broadcast_recipients terms.
func ByBroadcastRecipients(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBroadcastRecipientsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEmailTemplatesCount orders the results by email_templates count.
func ByEmailTemplatesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEmailTemplatesStep(), opts...)
	}
}

// ByEmailTemplates orders the results by email_templates terms.
func ByEmailTemplates(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEmailTemplatesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAutomationsCount orders the results by automations count.
func ByAutomationsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAutomationsStep(), opts...)
	}
}

// ByAutomations orders the results by automations terms.
func ByAutomations(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAutomationsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAutomationRunsCount orders the results by automation_runs count.
func ByAutomationRunsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAutomationRunsStep(), opts...)
	}
}

// ByAutomationRuns orders the results by automation_runs terms.
func ByAutomationRuns(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAutomationRunsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByWebhookEndpointsCount orders the results by webhook_endpoints count.
func ByWebhookEndpointsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newWebhookEndpointsStep(), opts...)
	}
}

// ByWebhookEndpoints orders the results by webhook_endpoints terms.
func ByWebhookEndpoints(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newWebhookEndpointsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySuppressionsCount orders the results by suppressions count.
func BySuppressionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSuppressionsStep(), opts...)
	}
}

// BySuppressions orders the results by suppressions terms.
func BySuppressions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSuppressionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newContactsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ContactsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ContactsTable, ContactsColumn),
	)
}
func newSegmentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SegmentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SegmentsTable, SegmentsColumn),
	)
}
func newEventsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EventsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EventsTable, EventsColumn),
	)
}
func newTrackingProfilesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TrackingProfilesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TrackingProfilesTable, TrackingProfilesColumn),
	)
}
func newTrackingVisitorsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TrackingVisitorsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, TrackingVisitorsTable, TrackingVisitorsColumn),
	)
}
func newAPITokensStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(APITokensInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, APITokensTable, APITokensColumn),
	)
}
func newIntegrationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(IntegrationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, IntegrationsTable, IntegrationsColumn),
	)
}
func newBroadcastsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BroadcastsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BroadcastsTable, BroadcastsColumn),
	)
}
func newBroadcastRecipientsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BroadcastRecipientsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BroadcastRecipientsTable, BroadcastRecipientsColumn),
	)
}
func newEmailTemplatesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EmailTemplatesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EmailTemplatesTable, EmailTemplatesColumn),
	)
}
func newAutomationsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AutomationsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AutomationsTable, AutomationsColumn),
	)
}
func newAutomationRunsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AutomationRunsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AutomationRunsTable, AutomationRunsColumn),
	)
}
func newWebhookEndpointsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(WebhookEndpointsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, WebhookEndpointsTable, WebhookEndpointsColumn),
	)
}
func newSuppressionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SuppressionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SuppressionsTable, SuppressionsColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
